Repository openshift/cluster-node-tuning-operator, pull requests merged in 2018-11, with the labels that each got.

#11 First steps towards custom profiles.
  Gopkg.lock
  Makefile
  assets/tuned/05-cm-tuned-profiles.yaml
  assets/tuned/06-cm-tuned-recommend.yaml
  assets/tuned/07-ds-tuned.yaml
  manifests/03-cr.yaml
  pkg/apis/tuned/v1alpha1/types.go
  pkg/controller/handler.go
  pkg/controller/objects.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XL

#13 Changing pattern & small build changes
  Makefile
  pkg/controller/tuned/tuned_controller.go
Labels: approved, lgtm, size/L

#14 Break up the recommend.conf in CR into structs.
  manifests/03-cr.yaml
  pkg/apis/tuned/v1alpha1/tuned_types.go
  pkg/apis/tuned/v1alpha1/zz_generated.deepcopy.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#15 Unify ConfigMap sync function
  Makefile
  assets/tuned/01-namespace.yaml
  assets/tuned/01-service-account.yaml
  assets/tuned/02-cluster-role.yaml
  assets/tuned/03-cluster-role-binding.yaml
  assets/tuned/04-cm-tuned-profiles.yaml
  assets/tuned/05-cm-tuned-recommend.yaml
  assets/tuned/06-ds-tuned.yaml
  manifests/04-rbac.yaml
  manifests/05-operator.yaml
  pkg/controller/tuned/tuned_controller.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#17 Add default CR creation under operator control.
  assets/tuned/07-cr-tuned.yaml
  manifests/03-rbac.yaml
  manifests/04-operator.yaml
  pkg/controller/tuned/tuned_controller.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#18 Adding owner references to objects created by the operator.
  manifests/03-rbac.yaml
  pkg/controller/tuned/tuned_controller.go
Labels: approved, lgtm, size/M

#19 Support for pod labels.
  assets/tuned/02-cluster-role.yaml
  assets/tuned/07-cr-tuned.yaml
  manifests/03-rbac.yaml
  pkg/apis/tuned/v1alpha1/tuned_types.go
  pkg/apis/tuned/v1alpha1/zz_generated.deepcopy.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#20 Pull the latest operator-sdk and cleanup.
  Gopkg.lock
  pkg/manifests/bindata.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/build.go
  vendor/github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/test/local.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/projutil/project_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/controller/reconcile.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/controller/status/types.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/controller/status/utils.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/controller/types.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/events/log_events.go
  vendor/github.com/operator-framework/operator-sdk/pkg/ansible/runner/eventapi/types.go
  vendor/github.com/operator-framework/operator-sdk/pkg/scaffold/build_dockerfile.go
  vendor/github.com/operator-framework/operator-sdk/pkg/scaffold/gopkgtoml.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/internal/testutils/testutils.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: approved, lgtm, size/XXL
