Repository openshift/cluster-node-tuning-operator, pull requests merged in 2018-10, with the labels that each got.

#2 Configurable resync interval, tuning profiles updates.
  assets/tuned/06-cm-tuned-profiles.yaml
  assets/tuned/08-ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  images/cluster-node-tuning-operator/Dockerfile
  manifests/05-operator.yaml
  pkg/manifests/bindata.go
  pkg/stub/handler.go
Labels: size/M

#3 Use privileged SCC for containerized tuned, RBAC cleanup.
  Makefile
  assets/tuned/03-cluster-role.yaml
  assets/tuned/03-scc-tuned.yaml
  assets/tuned/04-cluster-role-binding.yaml
  assets/tuned/04-cluster-role.yaml
  assets/tuned/05-cm-tuned-profiles.yaml
  assets/tuned/06-cm-tuned-recommend.yaml
  assets/tuned/07-ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  images/cluster-node-tuning-operator/Dockerfile
  manifests/01-namespace.yaml
  manifests/04-rbac.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: size/L

#4 Moving Dockerfile to top level directory.
  Dockerfile
  Makefile
  pkg/manifests/bindata.go
Labels: lgtm, size/XS

#5 Tolerate all taints so that tuned is always present on all nodes.
  assets/tuned/06-cm-tuned-recommend.yaml
  assets/tuned/07-ds-tuned.yaml
Labels: lgtm, size/XS

#6 Adding a test target for integration with Prow.
  Makefile
Labels: size/XS

#9 add namespace to manifests
  manifests/04-rbac.yaml
  manifests/05-operator.yaml
Labels: size/XS

#10 Add an operator env variable for the cluster-node-tuned image.
  Makefile
  assets/tuned/07-ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  manifests/05-operator.yaml
  manifests/image-references
  pkg/controller/handler.go
  pkg/controller/objects.go
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L
