Repository openshift/cluster-node-tuning-operator, pull requests merged in 2019-02, with the labels that each got.

#36 Switch to glog and integrate with klog.
  cmd/manager/main.go
  manifests/04-operator.yaml
  pkg/config/config.go
  pkg/controller/tuned/status.go
  pkg/controller/tuned/tuned_controller.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/L

#37 Rename cluster-node-tuning ClusterOperator
  manifests/04-operator.yaml
  pkg/config/config.go
Labels: approved, lgtm

#39 Fixup cluster operator resource
  Gopkg.lock
  manifests/04-operator.yaml
  manifests/05-clusteroperator.yaml
  pkg/config/config.go
  pkg/controller/tuned/status.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_registries.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/osin/v1/register.go
  vendor/github.com/openshift/api/osin/v1/types.go
  vendor/github.com/openshift/api/osin/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_kubescheduler.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/fake/fake_serviceca.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/kubescheduler.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/operator_client.go
  vendor/github.com/openshift/client-go/operator/clientset/versioned/typed/operator/v1/serviceca.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/interface.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/kubescheduler.go
  vendor/github.com/openshift/client-go/operator/informers/externalversions/operator/v1/serviceca.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/kubescheduler.go
  vendor/github.com/openshift/client-go/operator/listers/operator/v1/serviceca.go
  vendor/github.com/openshift/library-go/pkg/assets/create/creater.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
Labels: approved, lgtm, size/XXL

#42 Retry loop for creating Tuned CR.
  assets/tuned/default-cr-tuned.yaml
  pkg/controller/tuned/tuned_controller.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#43 status: report cluster operator version from payload
  manifests/04-operator.yaml
  manifests/05-clusteroperator.yaml
  pkg/controller/tuned/status.go
Labels: approved, lgtm, size/S
