Repository openshift/cluster-node-tuning-operator, pull requests merged in 2019-05, with the labels that each got.

#50 Fix tolerations
  manifests/04-operator.yaml
Labels: approved, lgtm, size/S

#51 Bug 1707050: set terminationMessagePolicy to FallbackToLogsOnError
  assets/tuned/06-ds-tuned.yaml
  manifests/04-operator.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#53 assests: fix duplicate resources key in container spec
  assets/tuned/06-ds-tuned.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#54 Remove pkg/manifests/bindata.go from the repo, generate it.
  Makefile
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#57 Increase operand's memory request and allow settings rollback.
  assets/tuned/06-ds-tuned.yaml
Labels: approved, lgtm, size/XS

#58 Do not update service account when it is already created.
  pkg/controller/tuned/tuned_controller.go
Labels: approved, lgtm, size/XS
