Repository openshift/cluster-node-tuning-operator, pull requests merged in 2019-01, with the labels that each got.

#27 Add version information to the operator.
  Makefile
  cmd/manager/main.go
Labels: approved, lgtm, size/S

#30 Restrict tuned to linux nodes
  assets/tuned/06-ds-tuned.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#31 Adding support for tuned "modules" and "scheduler" plugins.
  README.md
  assets/tuned/06-ds-tuned.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#33 CVO managed operator should deploy to masters
  manifests/04-operator.yaml
Labels: approved, lgtm, size/XS

#34 set cpu request for pod and operator
  assets/tuned/06-ds-tuned.yaml
  manifests/04-operator.yaml
Labels: approved, lgtm, size/XS
