Repository openshift/cluster-node-tuning-operator, pull requests merged in 2019-06, with the labels that each got.

#60 Vendor-in latest version of maintained go-bindata.
  Gopkg.lock
  Gopkg.toml
  Makefile
  vendor/github.com/kevinburke/go-bindata/.gitignore
  vendor/github.com/kevinburke/go-bindata/.mailmap
  vendor/github.com/kevinburke/go-bindata/.travis.yml
  vendor/github.com/kevinburke/go-bindata/AUTHORS.txt
  vendor/github.com/kevinburke/go-bindata/CONTRIBUTING.md
  vendor/github.com/kevinburke/go-bindata/LICENSE
  vendor/github.com/kevinburke/go-bindata/Makefile
  vendor/github.com/kevinburke/go-bindata/README.md
  vendor/github.com/kevinburke/go-bindata/asset.go
  vendor/github.com/kevinburke/go-bindata/bits.go
  vendor/github.com/kevinburke/go-bindata/bytewriter.go
  vendor/github.com/kevinburke/go-bindata/config.go
  vendor/github.com/kevinburke/go-bindata/convert.go
  vendor/github.com/kevinburke/go-bindata/debug.go
  vendor/github.com/kevinburke/go-bindata/doc.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/main.go
  vendor/github.com/kevinburke/go-bindata/go-bindata/version.go
  vendor/github.com/kevinburke/go-bindata/release.go
  vendor/github.com/kevinburke/go-bindata/restore.go
  vendor/github.com/kevinburke/go-bindata/safefile.go
  vendor/github.com/kevinburke/go-bindata/stringwriter.go
  vendor/github.com/kevinburke/go-bindata/testdata/symlinkFile/file1
  vendor/github.com/kevinburke/go-bindata/testdata/symlinkParent/symlinkTarget
  vendor/github.com/kevinburke/go-bindata/testdata/symlinkRecursiveParent/symlinkTarget
  vendor/github.com/kevinburke/go-bindata/toc.go
Labels: approved, lgtm, size/XXL

#62 Add more RelatedObjects for the must-gather tool.
  manifests/04-operator.yaml
  pkg/controller/tuned/status.go
Labels: approved, lgtm, size/S

#63 Bug 1718842: Operator-assisted removal of detached tuned secrets.
  assets/tuned/06-ds-tuned.yaml
  manifests/03-rbac.yaml
  pkg/controller/tuned/tuned_controller.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#66 use GA kubelet OS label
  assets/tuned/06-ds-tuned.yaml
Labels: approved, lgtm, size/XS

#67 Bug 1719967: Implement leader-for-life election.
  Gopkg.lock
  cmd/manager/main.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
