Repository openshift/cluster-node-tuning-operator, pull requests merged in 2020-10, with the labels that each got.

#159 Bug 1884287: Upgrade to klog v2.
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/manifests/manifests.go
  pkg/operator/controller.go
  pkg/operator/leader.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/operator/status.go
  pkg/tuned/host_payload.go
  pkg/tuned/tuned.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#114 Remove Docker as image build engine
  Makefile
Labels: approved, lgtm, size/S

#160 Remove traces of unsigned RPMs from the image.
  Dockerfile
  Dockerfile.rhel7
  Dockerfile.rhel8
Labels: approved, lgtm

#163 Updating cluster-node-tuning-operator builder & base images to be consistent with ART
  Dockerfile.rhel8
Labels: approved, lgtm

#165 Bug 1887088: image-references: no longer require cluster-node-tuned
  manifests/image-references
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#167 add current profile annotations to CVO manifests
  manifests/01-namespace.yaml
  manifests/02-crd-profile.yaml
  manifests/02-crd-tuned.yaml
  manifests/03-rbac.yaml
  manifests/04-operator.yaml
  manifests/05-clusteroperator.yaml
Labels: approved, lgtm

#168 Ship the latest version of stalld.
  assets/tuned/stalld/Makefile
  assets/tuned/stalld/src/stalld.c
  assets/tuned/stalld/src/stalld.h
  assets/tuned/stalld/src/throttling.c
  assets/tuned/stalld/src/utils.c
Labels: approved, lgtm

#169 Set scheduling policy to SCHED_FIFO to stalld and lower threshold.
  pkg/tuned/host_payload.go
Labels: approved, lgtm
