Repository openshift/cluster-node-tuning-operator, pull requests merged in 2020-03, with the labels that each got.

#108 Bug 1795665: Do not set owner references on tuned ServiceAccount
  Dockerfile.rhel7
  pkg/controller/tuned/tuned_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#109 Bug 1795671: Do not set owner references on tuned ServiceAccount (4.2)
  Dockerfile.rhel7
  pkg/controller/tuned/tuned_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#117 Retry handling of profile changes on errors.
  Makefile
  pkg/tuned/tuned.go
Labels: approved, lgtm, size/S

#116 Add dagrayvid to reviewers
  OWNERS
Labels: approved, lgtm, size/XS
