Repository openshift/cluster-node-tuning-operator, pull requests merged in 2020-11, with the labels that each got.

#172 Generating tuned CRD without any manual intervention.
  Makefile
  manifests/02-crd-tuned.yaml
  manifests/02-crd-tuned.yaml-patch
  pkg/apis/tuned/v1/tuned_types.go
Labels: approved, lgtm

#173 Change the priorities of example and e2e test profiles.
  examples/cpu-partitioning.yaml
  examples/elasticsearch.yaml
  examples/hugepages.yaml
  examples/ingress.yaml
  examples/realtime-mc.yaml
  examples/realtime.yaml
  test/e2e/testing_manifests/kernel_parameter_add_rm-child.yaml
  test/e2e/testing_manifests/kernel_parameter_add_rm-parent.yaml
  test/e2e/testing_manifests/stalld.yaml
Labels: approved, lgtm

#175 Bug 1895919: Add a weak dependency on kmod to tuned.
  assets/tuned/patches/090-kmod-weak-dependency.diff
  test/e2e/basic/modules.go
  test/e2e/reboots/stalld.go
  test/e2e/testing_manifests/tuned_modules_load.yaml
  test/e2e/util/util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ¯\_(ツ)_/¯

#177 Add IBM Cloud managed annotations to CVO manifests
  manifests/01-namespace.yaml
  manifests/02-crd-profile.yaml
  manifests/02-crd-tuned.yaml
  manifests/03-rbac.yaml
  manifests/04-operator.yaml
  manifests/05-clusteroperator.yaml
Labels: approved, lgtm

#180 Switch the upstream Dockerfile to CentOS 8.
  Dockerfile
  Dockerfile.rhel8
Labels: approved, lgtm

#181 Bug 1900196: Automatically restart stalld after exit.
  pkg/tuned/host_payload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#174 Allow selective debugging of the Tuned daemon.
  README.md
  manifests/20-crd-profile.yaml
  manifests/20-crd-tuned.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
  pkg/tuned/tuned.go
Labels: approved, lgtm

#183 E2e test cleanup.
  manifests/50-operator.yaml
  test/e2e/basic/available.go
  test/e2e/basic/custom_node_labels.go
  test/e2e/basic/custom_pod_labels.go
  test/e2e/basic/default_irq_smp_affinity.go
  test/e2e/basic/default_node_sysctl.go
  test/e2e/basic/modules.go
  test/e2e/basic/sysctl_d_override.go
  test/e2e/reboots/kernel_parameter_add_rm.go
  test/e2e/reboots/machine_config_labels.go
  test/e2e/reboots/stalld.go
  test/e2e/util/util.go
Labels: approved, lgtm
