Repository openshift/cluster-node-tuning-operator, pull requests merged in 2021-07, with the labels that each got.

#243 openshift-tuned event-driven change processing
  pkg/operator/controller.go
  pkg/tuned/tuned.go
Labels: approved, lgtm

#246 Updating to the latest stalld v1.13.0.
  assets/tuned/stalld/Makefile
  assets/tuned/stalld/src/stalld.c
  assets/tuned/stalld/src/stalld.h
  assets/tuned/stalld/src/utils.c
Labels: approved, lgtm

#247 Bug 1980788: Updating to the latest stalld v1.13.0.
  assets/tuned/stalld/Makefile
  assets/tuned/stalld/src/stalld.c
  assets/tuned/stalld/src/stalld.h
  assets/tuned/stalld/src/throttling.c
  assets/tuned/stalld/src/utils.c
  pkg/tuned/host_payload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#252 IBM Cloud manifest profile patch for operator deployment
  Makefile
  go.mod
  go.sum
  manifests/50-operator-ibm-cloud-managed.yaml
  manifests/50-operator.yaml
  profile-patches/ibm-cloud-managed/50-operator.yaml-patch
  tools/tools.go
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/doc.go
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/doc.go
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/help.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/openshift/build-machinery-go/scripts/doc.go
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/github.com/openshift/build-machinery-go/scripts/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm

#249 Address a race in the stalld e2e test.
  test/e2e/reboots/stalld.go
Labels: approved, lgtm

#250 scheduler: new option cgroup_ps_blacklist
  assets/tuned/patches/040-cgroup_ps_blacklist.diff
Labels: approved, lgtm

#256 Bug 1986477: Handle kube-apiserver disruption more gracefully.
  pkg/operator/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
