Repository openshift/cluster-node-tuning-operator, pull requests merged in 2021-02, with the labels that each got.

#200 Bug 1924081: Ship the latest tuned-2.15.0
  Makefile
  assets/tuned/daemon/92-tuned.install
  assets/tuned/daemon/doc/manual/modules/performance/ref_available-tuned-plug-ins.adoc
  assets/tuned/daemon/man/tuned-adm.8
  assets/tuned/daemon/tuned.spec
  assets/tuned/daemon/tuned/consts.py
  assets/tuned/daemon/tuned/plugins/plugin_bootloader.py
  assets/tuned/daemon/tuned/plugins/plugin_scheduler.py
  assets/tuned/daemon/tuned/plugins/plugin_service.py
  assets/tuned/daemon/tuned/utils/commands.py
  assets/tuned/daemon/tuned/version.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#201 Bug 1925072: Updating to the latest stalld v1.7.0.
  Dockerfile
  Dockerfile.rhel7
  Dockerfile.rhel8
  assets/tuned/stalld/Makefile
  assets/tuned/stalld/README.md
  assets/tuned/stalld/scripts/throttlectl.sh
  assets/tuned/stalld/src/stalld.c
  assets/tuned/stalld/src/stalld.h
  assets/tuned/stalld/src/throttling.c
  assets/tuned/stalld/src/utils.c
  pkg/tuned/host_payload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#202 Bug 1925072: Remove architecture specific gcc flags.
  assets/tuned/stalld/Makefile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#188 Add status conditions and profile applied to Profile(s)
  Makefile
  manifests/20-crd-profile.yaml
  manifests/20-crd-tuned.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/tuned/status.go
  pkg/tuned/tuned.go
  test/e2e/basic/available.go
  test/e2e/basic/profile_status.go
  test/e2e/basic/tuned_errors_and_recovery.go
  test/e2e/testing_manifests/cause-tuned-failure.yaml
  test/e2e/util/util.go
Labels: approved, lgtm

#206 Add more related objects to ClusterOperator.
  pkg/operator/status.go
Labels: approved, lgtm

#205 Support for adjusting netdev queue count.
  assets/tuned/patches/020-netdev.diff
Labels: approved, lgtm

#203 Remove Dockerfile.rhel7 no longer needed
  Dockerfile.rhel7
Labels: approved, lgtm

#208 Do not include *-patch files in /manifests.
  Dockerfile
  Dockerfile.rhel8
Labels: approved, lgtm

#209 stalld: Remove another architecture specific gcc flag
  assets/tuned/stalld/Makefile
Labels: approved, lgtm

#207 Bug 1926903: Instantiate the stalld systemd unit as disabled.
  assets/tuned/patches/030-service-enable-disable.diff
  pkg/tuned/host_payload.go
  test/e2e/reboots/stalld.go
  test/e2e/testing_manifests/stalld-disable.yaml
  test/e2e/util/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#197 Bug 1920525: Recover gracefully after Tuned errors.
  pkg/tuned/tuned.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#211 Bug 1926903: Keep ignition units in sync with [service] plugin.
  assets/tuned/patches/030-service-enable-disable.diff
  go.mod
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/operator/controller.go
  pkg/tuned/host_payload.go
  pkg/tuned/tuned.go
  pkg/util/ptr_cmp.go
  test/e2e/basic/default_irq_smp_affinity.go
  test/e2e/reboots/stalld.go
  vendor/gopkg.in/ini.v1/.gitignore
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/data_source.go
  vendor/gopkg.in/ini.v1/deprecated.go
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/helper.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
