Repository openshift/cluster-node-tuning-operator, pull requests merged in 2021-12, with the labels that each got.

#293 Bug 2029371: controller: update MC after application by TuneD
  pkg/operator/controller.go
  pkg/operator/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#296 controller: ignore non-linux hosts
  pkg/operator/controller.go
Labels: lgtm, approved

#299 build-machinery-go: bump to the latest version
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved

#288 openshift-tuned: TuneD built-in function support
  Makefile
  pkg/tuned/controller.go
  pkg/tuned/tuned_parser.go
  pkg/tuned/tuned_parser_test.go
  test/e2e/basic/tuned_builtin_expand.go
  test/e2e/testing_manifests/tuned_builtin_expand.yaml
Labels: lgtm, approved

#298 e2e: stalld and sysctl_d_override e2e test changes
  test/e2e/basic/sysctl_d_override.go
  test/e2e/reboots/stalld.go
Labels: lgtm, approved

#303 TuneD: switch to FDP TuneD delivery
  Dockerfile.rhel8
  Makefile
  assets/tuned/daemon/profiles/functions
  assets/tuned/daemon/profiles/openshift/tuned.conf
  assets/tuned/daemon/recommend.conf
  assets/tuned/daemon/tests/beakerlib/Program-tuned-tried-to-access-dev-mem-between/runtest.sh
  assets/tuned/daemon/tests/beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/runtest.sh
  assets/tuned/daemon/tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
  assets/tuned/daemon/tests/beakerlib/error-messages/runtest.sh
  assets/tuned/daemon/tests/beakerlib/tuned-adm-functionality/runtest.sh
  assets/tuned/daemon/tests/unit/profiles/test_loader.py
  assets/tuned/daemon/tests/unit/profiles/test_locator.py
  assets/tuned/daemon/tests/unit/profiles/test_variables.py
  assets/tuned/daemon/tests/unit/utils/test_global_config.py
  assets/tuned/daemon/tuned-gui.py
  assets/tuned/daemon/tuned.spec
  assets/tuned/daemon/tuned/consts.py
  assets/tuned/daemon/tuned/gtk/gui_plugin_loader.py
  assets/tuned/daemon/tuned/gtk/gui_profile_loader.py
  assets/tuned/daemon/tuned/gtk/gui_profile_saver.py
  assets/tuned/daemon/tuned/profiles/loader.py
  assets/tuned/daemon/tuned/profiles/locator.py
  assets/tuned/daemon/tuned/profiles/variables.py
  assets/tuned/daemon/tuned/utils/global_config.py
  assets/tuned/daemon/tuned/utils/profile_recommender.py
  assets/tuned/patches/040-openshift-profiles-aws.diff
Labels: lgtm, approved

#304 TuneD profiles: switch to FDP TuneD delivery completely
  Dockerfile.rhel8
Labels: lgtm, approved

#297 Bug 2026387: Handle certificate rotation in pkg/metrics/server.go
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  test/e2e/basic/metrics_cert_rotation.go
  test/e2e/util/util.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#306 [release-4.9] Bug 2033755: build-machinery-go: bump to the latest version
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
