Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-07, with the labels that each got.

#368 e2e: performance profile: Latency tests stabilization
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
  test/e2e/performanceprofile/functests/utils/images/prepull.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved

#369 PAO: update README.txt
  test/e2e/performanceprofile/functests/README.md
  test/e2e/performanceprofile/functests/README.txt
Labels: lgtm, approved

#381 Bug 2102109: Remove stale Profiles.
  pkg/operator/controller.go
  pkg/tuned/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#385 Switch to CentOS Stream for upstream Containerfile
  Dockerfile
Labels: lgtm, approved

#394 Fix wrong PAO upgrading kubelet test
  test/e2e/performanceprofile/functests/2_performance_update/kubelet.go
Labels: lgtm, approved

#389 Fix typo realTime Hint in PerformanceProfile.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.yaml
Labels: lgtm, approved

#397 Add clientset.go missing pkg/generated file
  pkg/generated/clientset/versioned/clientset.go
Labels: lgtm, approved

#391 Clean up file and fix API docs
  docs/performanceprofile/performance_profile.md
  hola
Labels: lgtm, approved

#376 makefile: enable running pao latency testing suite
  Makefile
  hack/build-latency-test-bin.sh
  hack/run-latency-testing.sh
Labels: lgtm, approved

#373 Rename Performance Addon Controller to Performance Profile Controller
  README.md
  docs/performanceprofile/api-versions.md
  docs/performanceprofile/configuration_hotfixes.md
  docs/performanceprofile/cpu-load-balancing.md
  docs/performanceprofile/interactions/README.md
  docs/performanceprofile/irq-load-balancing.md
  docs/performanceprofile/kubelet-config-snippets.md
  docs/performanceprofile/performance_controller.md
  docs/performanceprofile/performance_profile.md
  docs/performanceprofile/runtime-class.md
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
Labels: lgtm, approved

#374 Bug 2105967: E2E test case Telco friendly workload hints
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#406 Dockerfile: provide full URL to CentOS stream image
  Dockerfile
Labels: lgtm, approved
