Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-05, with the labels that each got.

#347 Add Hyper-threading aware scheduling test cases for PerformanceProfile.
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, ok-to-test

#345 Add performanceProfile API offline cores
  assets/performanceprofile/scripts/set-cpus-offline.sh
  docs/performanceprofile/performance_profile.md
  examples/performanceprofile/samples/performance_v2_performanceprofile.yaml
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
  pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/controller/performanceprofile/components/utils.go
  pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
  pkg/performanceprofile/utils/testing/testing.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved

#357 Bug 2080123: Ignore Profile updates triggered by old operands
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/tuned/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#360 Add e2e offlined cpus
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved

#361 Bug 2083482: Ignore Profile updates triggered by old operands
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/tuned/tuned.go
  test/e2e/reboots/stalld.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#362 Remove conversion test for workload hints
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved

#354 Bug 2087159: Modify PPC to generate new "offlined" parameter in Performance Profile
  cmd/performance-profile-creator/cmd/root.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
  test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4b.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4c.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5a.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5b.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#363 Bug 2089414: PAO Add validation check between isolated and offlined CPUs
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified

#367 Bug 2083428: crio: Use absolute path for binaries in crio hook script
  assets/performanceprofile/scripts/low-latency-hooks.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
