Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-09, with the labels that each got.

#448 hack: performance: skip tests under 5_latency_testing
  hack/run-functests.sh
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved

#455 OCPBUGS-851: [release-4.11] Dockerfile: provide full URL to CentOS stream image #406
  Dockerfile
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug

#426 Improve tuned test suite
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/utils/testing/testing.go
Labels: lgtm, approved

#460 Remove RPS configuration wihen realtime workload hint is explicitly set to false
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved

#458 OCPBUGS-63: e2e: performance: Update PP isolated cpus
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#456 HyperShift: Create ConfigMaps for NTO-generated MachineConfigs
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/util/strings_map.go
Labels: lgtm, approved

#462 Performance profile Annotation to enable RPS
  docs/performanceprofile/configuration_hotfixes.md
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved

#471 e2e: Fix metrics_cert_rotation.go
  test/e2e/basic/metrics_cert_rotation.go
  test/e2e/util/util.go
Labels: lgtm, approved

#464 Add verification on kernel param rcutree.kthread
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, ok-to-test

#470 Skip should set offline cpus after deploy PAO test
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved

#415 Implement new workloadHint perPodPowerManagement
  assets/performanceprofile/tuned/openshift-node-performance
  docs/performanceprofile/performance_profile.md
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v1/performanceprofile_types.go
  pkg/apis/performanceprofile/v1/zz_generated.deepcopy.go
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
  pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/utils/testing/testing.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved

#449 Create HACKING.md file
  HACKING.md
Labels: lgtm, approved

#467 OCPBUGS-1131: [release-4.11] e2e: perfprof: unbreak the e2e-gcp PAO lane
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#468 workloadHints not included in validateFields()
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved

#474 Clean output of kernel args if no hugepages or additional args are present
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved

#475 Set default RealTime hint to true and add to conversion
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved

#476 Adjust nto_custom_profiles:count metric to count by _id
  manifests/30-monitoring.yaml
Labels: lgtm, approved
