Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-11, with the labels that each got.

#495 OCPBUGSM-47141: Apply RPS mask for each RX queues
  assets/performanceprofile/scripts/set-rps-mask.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved

#483 OCPBUGS-3324: RPS mask test fixes
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#507 OCPBUGS-1334: Configure ktimers scheduler priority to match ksoftirqsd's
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#499 pao: latency-tests: read test log directly from pod
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved

#380 OCPBUGS-1566: E2E test for offline cpus
  test/e2e/performanceprofile/functests/2_performance_update/nodes_test.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#513 Configuration hotfixes documentation fixes
  docs/performanceprofile/configuration_hotfixes.md
Labels: lgtm, approved

#508 [release-4.11] [manual] OCPBUGS-3182: set RPS for veth on host level only
  assets/performanceprofile/configs/99-low-latency-hooks.json
  assets/performanceprofile/configs/99-netdev-rps.rules
  assets/performanceprofile/scripts/low-latency-hooks.sh
  assets/performanceprofile/scripts/set-rps-mask.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#510 [release-4.11] OCPBUGS-3474: Add ktimer to PAO tuned profile
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug

#485 e2e: performance profile: add logs and minor fixes
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
Labels: lgtm, approved
