Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-04, with the labels that each got.

#334 Embed performance profile docs
  Makefile
  README.md
  docs/performanceprofile/api-versions.md
  docs/performanceprofile/ci.md
  docs/performanceprofile/configuration_hotfixes.md
  docs/performanceprofile/cpu-load-balancing.md
  docs/performanceprofile/interactions/README.md
  docs/performanceprofile/interactions/diagram.png
  docs/performanceprofile/interactions/diagram.svg
  docs/performanceprofile/interactions/performance-profile.yaml
  docs/performanceprofile/irq-load-balancing.md
  docs/performanceprofile/kubelet-config-snippets.md
  docs/performanceprofile/pao-icon.svg
  docs/performanceprofile/performance_addon.md
  docs/performanceprofile/performance_profile.md
  docs/performanceprofile/runtime-class.md
  docs/performanceprofile/troubleshooting.md
  hack/docs-generate.sh
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  tools/docs-generator/docs-generator.go
Labels: lgtm, approved

#333 Bug 2066700: RBAC replace wildcards for tuned.openshift.io apiGroup
  manifests/40-rbac.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#337 Update NTO-generated annotations in MCs
  pkg/operator/controller.go
Labels: lgtm, approved

#335 Add pao engineers to designated owner files
  OWNERS
Labels: lgtm, approved

#325 PerformanceProfileCreator build and functional test execution adaptation.
  Dockerfile
  Dockerfile.rhel8
  Makefile
  cmd/performance-profile-creator/README.md
  hack/run-perf-profile-creator.sh
  test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
Labels: lgtm, approved, ok-to-test

#336 Fix PAO OLM operator removal
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
Labels: lgtm, approved

#338 Fix broken links in PAO docs
  docs/performanceprofile/api-versions.md
  docs/performanceprofile/configuration_hotfixes.md
  docs/performanceprofile/performance_addon.md
Labels: lgtm, approved

#324 Performance profile render command integration
  Makefile
  cmd/cluster-node-tuning-operator/main.go
  docs/performanceprofile/performance_addon.md
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_suite_test.go
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved

#342 Bug 2073938: Replace RuntimeClass version from v1beta1 to v1
  pkg/performanceprofile/controller/performanceprofile/components/manifestset/manifestset.go
  pkg/performanceprofile/controller/performanceprofile/components/runtimeclass/runtimeclass.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/3_performance_status/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#340 Fix performance profile deepcopy generation
  pkg/apis/performanceprofile/v1/doc.go
  pkg/apis/performanceprofile/v1/performanceprofile_types.go
  pkg/apis/performanceprofile/v1/zz_generated.deepcopy.go
  pkg/apis/performanceprofile/v2/doc.go
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
Labels: lgtm, approved

#339 Implement a new workload hints functionality
  assets/performanceprofile/tuned/openshift-node-performance
  docs/performanceprofile/performance_profile.md
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/performance_test.go
  pkg/apis/performanceprofile/v1/performanceprofile_types.go
  pkg/apis/performanceprofile/v1/zz_generated.deepcopy.go
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
  pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved

#344 Adapt PPC to use workload hints instead of setting additional kernel arguments
  cmd/performance-profile-creator/cmd/root.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
  test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile1.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile2.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile3.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile4.yaml
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.json
  test/e2e/performanceprofile/testdata/ppc-expected-profiles/profile5.yaml
Labels: lgtm, approved

#343 Add build and ppc test invocation under one target
  Makefile
Labels: lgtm, approved

#351 Fix local e2e test target
  Makefile
Labels: lgtm, approved

#352 Bug 2024682: controller: update MC after application by TuneD
  manifests/20-crd-profile.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/tuned/status.go
  pkg/tuned/tuned.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#346 Move PAO OLM removal to main
  cmd/cluster-node-tuning-operator/main.go
  go.sum
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_suite_test.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/utils/client/clients.go
  vendor/github.com/operator-framework/api/pkg/operators/install/install.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#355 Bug 2078969: Ignore Profile updates triggered by old operands
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/tuned/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
