Repository openshift/cluster-node-tuning-operator, pull requests merged in 2022-10, with the labels that each got.

#466 OCPBUGS-1126: [release-4.11] irqbalance: add unit to clear the cpu ban list
  assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#479 OCPBUGSM-47141: set RPS for veth only at host level
  assets/performanceprofile/configs/99-low-latency-hooks.json
  assets/performanceprofile/configs/99-netdev-rps.rules
  assets/performanceprofile/scripts/low-latency-hooks.sh
  assets/performanceprofile/scripts/set-rps-mask.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved

#480 OCPBUGS-2167: Workload hints backwards compatibility intel_pstate=disable
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#486 e2e: perfprof: get cpus from node capacity
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved

#481 HyperShift: avoid unnecessary mcfg creation
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
Labels: lgtm, approved

#491 HyperShift: rename Tuned ConfigMap key from tuned to tuning
  pkg/operator/hypershift.go
Labels: lgtm, approved

#482 udev-rule: rationale for applying the rule on virtual interfaces
  assets/performanceprofile/configs/99-netdev-rps.rules
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved

#487 OCPBUGS-764: [release-4.11] Add intel_pstate=disable to default configuration with no hints (#480)
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance/performance_profile.yaml
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#494 e2e: perfprof: remove broken test
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved

#492 OCPBUGS-2437: Filter out copied csvs when removing pao CSV
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug

#422 Bug 2115802: Get latest profile before updating and use nodes.GetKubeletConfig
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
