Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-05, with the labels that each got.

#641 OCPBUGS-10424: e2e: Fix RPS test for multi-worker cluster
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#626 OCPBUGS-11083: pao e2e: fix update test suit timeouts
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#644 OCPBUGS-12978: use WatchNamespace() when deleting Profiles
  pkg/operator/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#646 OCPBUGS-13148: Configure cpu balancing cpu sets for all clusters
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, jira/valid-reference

#582 OCPBUGS-13262: Add PerformanceProfiles to 'oc adm must-gather'
  pkg/operator/status.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#654 OCPBUGS-13262: Add PerformanceProfiles to 'oc adm must-gather: REVERT
  pkg/operator/status.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#655 OCPBUGS-13262: Add PerformanceProfiles to 'oc adm must-gather'
  pkg/operator/status.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#633 OCPBUGS-12723: Address CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/language/language.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#642 [release-4.13] [manual] OCPBUGS-11336: pao e2e: fix update test suit timeouts
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#643 [release-4.13] OCPBUGS-11709: pao e2e: skip hugepages and numa tests properly
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#653 OCPBUGS-14137: e2e: perfprof: add SNO device recovery test
  test/e2e/performanceprofile/functests/8_reboot/devices.go
  test/e2e/performanceprofile/functests/8_reboot/test_suite_reboot_test.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#564 OCPBUGS-5529: Fix updating numa core siblings map in GetCpuSiblings function
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#584 OCPBUGS-11821: check ocp version and export CNF_TEST_IMAGE variable with appropriate…
  hack/run-functests.sh
  hack/run-latency-testing.sh
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference
