Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-02, with the labels that each got.

#561 Refactor IRQ load balancing enable/disable test
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved

#538 render: initialize klog flag
  hack/render-sync.sh
  pkg/performanceprofile/cmd/render/cmd.go
  pkg/performanceprofile/cmd/render/render.go
Labels: lgtm, approved

#509 OCPBUGS-5064: E2E: Per Core Runtime Tuning Test automation
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#566 Report host-level sysctls in conflict with TuneD ones
  pkg/tuned/controller.go
  pkg/tuned/status.go
Labels: lgtm, approved

#567 OCPBUGS-7384: Remove optimization to allow full resync
  pkg/tuned/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#570 OCPBUGS-7745: Remove trailing spaces from test names
  pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#568 [release-4.12] OCPBUGS-7586: E2E: Per Core Runtime Tuning Test automation
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#558 Handle different # of CPUs are in the same MCP
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/status.go
  pkg/tuned/controller.go
Labels: lgtm, approved
