Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-01, with the labels that each got.

#537 Skip offline multiple ranges test if number of cores less than 20
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved

#540 Remove trailing space from test name
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
Labels: lgtm, approved

#523 [release-4.11] OCPBUGS-1567: E2E: Automate Offline CPUs feature
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#531 [release-4.11] [manual] OCPBUGS-5020: pao: latency-tests: read test log directly from pod
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#532 OCPBUGS-5528: Run node selector tests only if we have 2 non Performance worker nodes
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#541 OCPBUGS-4647: Add authentication to the /metrics endpoint
  pkg/client/listers.go
  pkg/metrics/server.go
  pkg/operator/controller.go
  pkg/tuned/controller.go
  pkg/util/os.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#542 update owners 20230109
  OWNERS
Labels: lgtm, approved

#550 OCPBUGS-6057: Skip watch on CA ConfigMap in HyperShift
  pkg/metrics/server.go
  pkg/operator/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#557 OCPBUGS-6822: Update NTO images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel8
  go.mod
  pkg/client/client.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/operator/profilecalculator.go
  pkg/performanceprofile/cmd/render/render.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
