Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-09, with the labels that each got.

#778 OCPBUGS-18052: feat: added logic to handle legacy sno install
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/cmd/render/render.go
  test/e2e/performanceprofile/cluster-setup/pinned-cluster/default/infrastructure.yaml
  test/e2e/performanceprofile/cluster-setup/pinned-cluster/single-node-legacy/infrastructure.yaml
  test/e2e/performanceprofile/cluster-setup/pinned-cluster/single-node-legacy/mc.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/pinned/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/pinned/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#757 [release-4.13] OCPBUGS-17688: update tsc karg to tsc=reliable
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#779 OCPBUGS-16908: Add SetLogger() prior to controller-runtime start
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  vendor/github.com/go-logr/zapr/.gitignore
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#774 [release-4.13] OCPBUGS-18063: cgroup: Match the name of the cgroup to what is expected by kubelet
  assets/performanceprofile/scripts/cpuset-configure.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#768 OCPBUGS-15044: e2e:irqloadbalance: wait for profile revert
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#777 OCPBUGS-18392: Change the OVN trigger file name to adapt to OVN IC
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#785 OCPBUGS-18480: Sync DaemonSet if operand image changes
  pkg/operator/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#787 OCPBUGS-18662: e2e:rps: improve logging
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#766 OCPBUGS-17941: Tighten the rules for modifying Tuned Profiles
  assets/tuned/manifests/ds-tuned.yaml
  manifests/20-profile.crd.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/operator/status.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/utils/testing/testing.go
  pkg/tuned/controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#719 e2e: add expected max latancy to hwlatdetec test & rename constant
  Makefile
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, acknowledge-critical-fixes-only

#773 OCPBUGS-18000: Release leader election on manager exit
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#794 Update required go version
  Dockerfile
  go.mod
Labels: lgtm, approved

#784 OCPBUGS-18650: Memory manager E2E test fixes
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#797 OCPBUGS-19351: Revert "Release leader election on manager exit
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#803 OCPBUGS-19351: Keep Profile status.bootcmdline around
  manifests/20-profile.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#804 OCPBUGS-19459: check for object being nil
  pkg/util/objectinfo.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#802 OCPBUGS-18000: Revert "Revert "Release leader election on manager exit (#773)" (#797)"
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#666 Add k8s reporter to e2e tests
  go.mod
  go.sum
  test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
  test/e2e/performanceprofile/functests/4_latency/test_suite_latency_test.go
  test/e2e/performanceprofile/functests/utils/consts.go
  test/e2e/performanceprofile/functests/utils/k8sreporter/reporter.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README.md
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/openshift-kni/k8sreporter/LICENSE
  vendor/github.com/openshift-kni/k8sreporter/README.md
  vendor/github.com/openshift-kni/k8sreporter/client.go
  vendor/github.com/openshift-kni/k8sreporter/reporter.go
  vendor/modules.txt
Labels: lgtm, approved

#806 OCPBUGS-14148: e2e: perfprof: add SNO device recovery test (#653)
  test/e2e/performanceprofile/functests/8_reboot/devices.go
  test/e2e/performanceprofile/functests/8_reboot/test_suite_reboot_test.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#809 OCPBUGS-19791:[release-4.12] e2e: add expected max latency to hwlatde…
  hack/run-latency-testing.sh
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#810 OCPBUGS-19795: Add kubeconfig path for IBM Managed OpenShift
  assets/tuned/manifests/ds-tuned.yaml
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#791 OCPBUGS-18783: e2e: perfprof: enhance the scheduling domain tests
  pkg/performanceprofile/utils/schedstat/schedstat.go
  pkg/performanceprofile/utils/schedstat/schedstat_test.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#814 OCPBUGS-19840: Add kubeconfig path for IBM Managed OpenShift
  assets/tuned/manifests/ds-tuned.yaml
  pkg/tuned/controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#815 Add the k8s reporter to the configuration suite
  test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
Labels: lgtm, approved

#792 Improve co/node-tuning operand version reporting
  pkg/operator/controller.go
  pkg/operator/status.go
Labels: lgtm, approved
