Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-07, with the labels that each got.

#703 e2e: RPS: fix expected cpu set
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved

#701 e2e: devmgr: fine tune kubelet restart test
  test/e2e/performanceprofile/functests/9_reboot/devices.go
Labels: lgtm, approved

#700 OCPVE-382: fix: add default state for crio config
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: lgtm, approved, jira/valid-reference

#559 Configure OVS for dynamic cpu pinning
  assets/performanceprofile/configs/01-use-ovs-slice.conf
  assets/performanceprofile/configs/ovs-enable-dynamic-cpu-affinity
  assets/performanceprofile/configs/ovs.slice
  assets/performanceprofile/scripts/cpuset-configure.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved

#702 e2e: perf-prof: disable truncating gomega output
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved

#706 e2e: latency testing: increase the expected threshold
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved

#590 e2e: overhaul Performance-Addon-Operator tests
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/3_performance_status/status.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved

#705 OCPBUGS-15738: Switch to rslave/HostToContainer volume mount propagation
  assets/tuned/manifests/ds-tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#704 OCPBUGS-15736: Do not rollback settings on TuneD exit
  assets/bin/run
  examples/ingress.yaml
  test/e2e/basic/rollback.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#710 OCPBUGS-15800:e2e: latency testing: increase the expected threshold and fix gomega truncating output
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#714 Build gather-sysinfo
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  Makefile
  cmd/gather-sysinfo/.gitignore
  cmd/gather-sysinfo/gather-sysinfo.go
  cmd/gather-sysinfo/gather-sysinfo_test.go
  go.mod
  go.sum
  vendor/github.com/openshift-kni/debug-tools/LICENSE
  vendor/github.com/openshift-kni/debug-tools/pkg/fswrap/fswrap.go
  vendor/github.com/openshift-kni/debug-tools/pkg/irqs/info.go
  vendor/github.com/openshift-kni/debug-tools/pkg/irqs/reporter.go
  vendor/github.com/openshift-kni/debug-tools/pkg/irqs/soft/info.go
  vendor/github.com/openshift-kni/debug-tools/pkg/k8s_imported/cpuset.go
  vendor/github.com/openshift-kni/debug-tools/pkg/k8s_imported/podresources_client.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/cpuaff.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/irqaff.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/irqwatch.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podinfo.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podres.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/types.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/root.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/wait.go
  vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/fakefsinfo.go
  vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/informer.go
  vendor/github.com/openshift-kni/debug-tools/pkg/machineinformer/relocatablesysfs.go
  vendor/github.com/openshift-kni/debug-tools/pkg/procs/info.go
  vendor/modules.txt
Labels: lgtm, approved

#695 OCPBUGS-15322: [release-4.13] E2E: Add memory manager sanity test case
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#712 E2E: update cpu load balancing test for latest cgroup related changes
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved

#716 Align TuneD with the latest shipped FDP version
  Makefile
  assets/tuned/daemon/Makefile
  assets/tuned/daemon/README
  assets/tuned/daemon/README.md
  assets/tuned/daemon/doc/manual/modules/performance/proc_creating-new-tuned-profiles.adoc
  assets/tuned/daemon/doc/manual/modules/performance/proc_installing-and-enabling-tuned.adoc
  assets/tuned/daemon/doc/manual/modules/performance/proc_modifying-existing-tuned-profiles.adoc
  assets/tuned/daemon/doc/manual/modules/performance/proc_setting-a-tuned-profile.adoc
  assets/tuned/daemon/experiments/powertop2tuned.py
  assets/tuned/daemon/man/tuned-adm.8
  assets/tuned/daemon/man/tuned-profiles-sap-hana.7
  assets/tuned/daemon/profiles/cpu-partitioning/00-tuned-pre-udev.sh
  assets/tuned/daemon/profiles/cpu-partitioning/script.sh
  assets/tuned/daemon/profiles/functions
  assets/tuned/daemon/profiles/laptop-ac-powersave/script.sh
  assets/tuned/daemon/profiles/openshift/tuned.conf
  assets/tuned/daemon/profiles/powersave/script.sh
  assets/tuned/daemon/profiles/realtime-virtual-guest/script.sh
  assets/tuned/daemon/profiles/realtime-virtual-host/script.sh
  assets/tuned/daemon/profiles/realtime/script.sh
  assets/tuned/daemon/profiles/sap-hana-kvm-guest/tuned.conf
  assets/tuned/daemon/profiles/spindown-disk/script.sh
  assets/tuned/daemon/tests/beakerlib/Expose-TuneD-API-to-the-Unix-Domain-Socket/main.fmf
  assets/tuned/daemon/tests/beakerlib/Expose-TuneD-API-to-the-Unix-Domain-Socket/runtest.sh
  assets/tuned/daemon/tests/beakerlib/Traceback-caused-by-scheduler-plugin-with/main.fmf
  assets/tuned/daemon/tests/beakerlib/Traceback-caused-by-scheduler-plugin-with/runtest.sh
  assets/tuned/daemon/tests/beakerlib/bz2071418-TuneD-exits-on-duplicate-config-lines-new/main.fmf
  assets/tuned/daemon/tests/beakerlib/bz2071418-TuneD-exits-on-duplicate-config-lines-new/runtest.sh
  assets/tuned/daemon/tuned-gui.py
  assets/tuned/daemon/tuned-main.conf
  assets/tuned/daemon/tuned.spec
  assets/tuned/daemon/tuned/admin/admin.py
  assets/tuned/daemon/tuned/consts.py
  assets/tuned/daemon/tuned/daemon/controller.py
  assets/tuned/daemon/tuned/daemon/daemon.py
  assets/tuned/daemon/tuned/plugins/base.py
  assets/tuned/daemon/tuned/plugins/instance/instance.py
  assets/tuned/daemon/tuned/plugins/plugin_bootloader.py
  assets/tuned/daemon/tuned/plugins/plugin_cpu.py
  assets/tuned/daemon/tuned/plugins/plugin_modules.py
  assets/tuned/daemon/tuned/plugins/plugin_scheduler.py
  assets/tuned/daemon/tuned/plugins/plugin_script.py
  assets/tuned/daemon/tuned/plugins/plugin_service.py
  assets/tuned/daemon/tuned/plugins/plugin_sysctl.py
  assets/tuned/daemon/tuned/plugins/plugin_sysfs.py
  assets/tuned/daemon/tuned/plugins/plugin_systemd.py
  assets/tuned/daemon/tuned/units/manager.py
Labels: lgtm, approved

#722 OCPBUGS-16401:tuned: remove sched_min_granularity_ns settings
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#720 pao: status: do not take address of loop var
  pkg/performanceprofile/controller/status.go
Labels: lgtm, approved

#721 OCPBUGS-15044: e2e:irqbalance: wait for tuned profile to be ready
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#724 Improve render error handling
  pkg/performanceprofile/cmd/render/render.go
Labels: lgtm, approved

#727 OCPBUGS-15044:e2e:irqbalance: applied condition exists
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#734 OCPBUGS-13429: pao: e2e: Split pao lanes in release-4.12 leftover
  hack/run-update-testing.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#739 Fix a race in e2e test rollback.go code
  test/e2e/basic/rollback.go
Labels: lgtm, approved
