Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-11, with the labels that each got.

#838 [release-4.12] OCPBUGS-21837: nto: pao avoid timeout when there are too many CSV
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/utils.go
  test/e2e/basic/csvs.go
  test/e2e/basic/operator_test.go
  test/e2e/testing_manifests/csv-dummy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#770 CNF-10294: main: remove deprecated multi ns function
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, jira/valid-reference

#837 NO-JIRA: Remove most //nolint:* overrides
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/performanceprofile/profilecreator/helper.go
  pkg/tuned/controller.go
  pkg/tuned/tuned_parser.go
Labels: lgtm, approved, jira/valid-reference

#846 OCPBUGS-20669: Disable HTTP/2 for webhook and metrics servers
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  go.sum
  pkg/metrics/server.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#848 CNF-10344: NTO: Avoid depending on kubernetes cpuset
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/controller/performanceprofile/components/utils.go
  pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  vendor/k8s.io/utils/cpuset/OWNERS
  vendor/k8s.io/utils/cpuset/cpuset.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#849 OCPBUGS-20661: Disable HTTP/2 for webhook and metrics servers
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  go.sum
  pkg/metrics/server.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#850 OCPBUGS-20651: Disable HTTP/2 for webhook and metrics servers
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  go.sum
  pkg/metrics/server.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/LICENSE
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#708 OCPBUGS-18649: E2E: PPC Test cases
  Makefile
  test/e2e/performanceprofile/functests/10_performance_ppc/10_ppc_suite_test.go
  test/e2e/performanceprofile/functests/10_performance_ppc/ppc.go
  test/e2e/performanceprofile/functests/utils/consts.go
  vendor/github.com/onsi/gomega/gbytes/buffer.go
  vendor/github.com/onsi/gomega/gbytes/io_wrappers.go
  vendor/github.com/onsi/gomega/gbytes/say_matcher.go
  vendor/github.com/onsi/gomega/gexec/build.go
  vendor/github.com/onsi/gomega/gexec/exit_matcher.go
  vendor/github.com/onsi/gomega/gexec/prefixed_writer.go
  vendor/github.com/onsi/gomega/gexec/session.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
