Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-06, with the labels that each got.

#609 [release-4.13][manual] OCPBUGS-11851: render: remove uid from render-sync target (#594)
  hack/render-sync.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#676 [release-4.11] OCPBUGS-14501: Fix updating numa core siblings map in GetCpuSiblings f…
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#679 OCPBUGS-14756: [test] [e2e] Check ci lanes are executing the right test suites
  hack/run-functests.sh
  hack/run-update-testing.sh
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#650 OCPBUGS-4194: rps: use default rps mask kernel API
  assets/performanceprofile/configs/99-default-rps-mask.conf
  assets/performanceprofile/configs/99-netdev-physical-rps.rules
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#631 OCPBUGS-14193: pao e2e: Split e2e PAO update lane to more lanes
  Makefile
  hack/run-functests.sh
  hack/run-latency-testing.sh
  hack/run-perf-profile-creator-functests.sh
  hack/run-render-command-functests.sh
  hack/run-test.sh
  hack/run-update-testing.sh
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/test_suite_performance_workloadhints_test.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#682 OCPBUGS-14934: consistent use of ginkgo flags in Makefile
  Makefile
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#688 [release-4.12] OCPBUGS-14958: Revert "Remove optimization to allow full resync (#569)"
  pkg/tuned/controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#689 OCPBUGS-12756: Add minLength restriction to Tuned CR
  manifests/20-tuned.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#634 Modify owners file
  OWNERS
Labels: lgtm, approved

#573 OCPBUGS-8344: Add memory manager sanity test case
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-low, jira/valid-bug, jira/valid-reference

#662 e2e: verify latency tests run with LATENCY_TEST_DELAY>120
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, ok-to-test

#672 test: perfprof: devices: fix default test image
  test/e2e/performanceprofile/functests/8_reboot/devices.go
Labels: lgtm, approved

#628 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  pkg/apis/performanceprofile/performance_test.go
  pkg/performanceprofile/cmd/render/render.go
  pkg/performanceprofile/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_suite_test.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, ok-to-test

#651 Expose TuneD socket to host.
  assets/bin/run
  assets/tuned/manifests/ds-tuned.yaml
Labels: lgtm, approved

#665 Use RHEL9 as a base
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel9
Labels: lgtm, approved

#693 e2e: memorymanager fix: check the hugepage size condition
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved

#690 OCPBUGS-12836: [pao] [e2e] flaky test test_id:28440 Updating of nodeSelector
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#697 e2e: reboot: add kubelet restart test
  Makefile
  test/e2e/performanceprofile/functests/9_reboot/devices.go
  test/e2e/performanceprofile/functests/9_reboot/test_suite_reboot_test.go
Labels: lgtm, approved

#699 OCPBUGS-13065: Do not rollback settings on TuneD exit
  assets/bin/run
  examples/ingress.yaml
  test/e2e/basic/rollback.go
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#692 OCPBUGS-14946: Switch to rslave/HostToContainer volume mount propagation
  assets/tuned/manifests/ds-tuned.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
