Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-10, with the labels that each got.

#807 OCPBUGS-19785: Set non-default UserAgent for easier debugging
  cmd/cluster-node-tuning-operator/main.go
  pkg/operator/controller.go
  pkg/tuned/controller.go
  version/version.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#731 OCPBUGS-14241: nto: pao avoid timeout when there are too many CSV
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/utils.go
  test/e2e/basic/csvs.go
  test/e2e/testing_manifests/csv-dummy.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#817 [release-4.14] OCPBUGS-20032: nto: pao avoid timeout when there are too many CSV
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/utils.go
  test/e2e/basic/csvs.go
  test/e2e/testing_manifests/csv-dummy.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#801 OCPVE-717: fix: add if check for no resource match error
  cmd/cluster-node-tuning-operator/main.go
  pkg/util/errors.go
  pkg/util/errors_test.go
Labels: lgtm, approved, jira/valid-reference

#793 Add golangci-lint
  .golangci.yaml
  Makefile
  cmd/cluster-node-tuning-operator/main.go
  cmd/gather-sysinfo/gather-sysinfo.go
  cmd/performance-profile-creator/cmd/root.go
  docs/performanceprofile/performance_profile.md
  examples/performanceprofile/crd/bases/performance.openshift.io_performanceprofiles.yaml
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v1/performanceprofile_types.go
  pkg/apis/performanceprofile/v1alpha1/performanceprofile_conversion.go
  pkg/apis/performanceprofile/v1alpha1/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_conversion.go
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/metrics/server.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/performanceprofile/cmd/render/cmd.go
  pkg/performanceprofile/cmd/render/manifests.go
  pkg/performanceprofile/cmd/render/render.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/utils.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/controller/status.go
  pkg/performanceprofile/controller/utils.go
  pkg/performanceprofile/profilecreator/helper.go
  pkg/performanceprofile/profilecreator/mcp.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/tuned/controller.go
  pkg/tuned/tuned_parser.go
  pkg/util/errors.go
  pkg/util/leaderelection.go
  tools/docs-generator/docs-generator.go
Labels: lgtm, approved

#823 Makefile: remote tmp folder on clean target
  Makefile
Labels: lgtm, approved

#790 OCPBUGS-18949: Tighten the rules for modifying Tuned Profiles
  assets/tuned/manifests/ds-tuned.yaml
  manifests/20-profile.crd.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/operator/status.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/utils/testing/testing.go
  pkg/tuned/controller.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#824 render: change directory path
  hack/render-sync.sh
Labels: lgtm, approved

#827 OCPBUGS-20567: Remove obsolete protocols and weak ciphers
  pkg/metrics/server.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#834 OCPBUGS-21932: Disable HTTP/2 for webhook and metrics servers
  cmd/cluster-node-tuning-operator/main.go
  pkg/metrics/server.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#829 OCPBUGS-13330: Use RHEL9 as a base
  .ci-operator.yaml
  Dockerfile
  Dockerfile.rhel9
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#782 [release-4.13][manual] OCPBUGS-18493: e2e: deflake IRQ load-balancing
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
