Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-08, with the labels that each got.

#743 e2e: remove image parameter from must gather
  test/e2e/performanceprofile/functests/6_mustgather_testing/test_suite_mustgather_test.go
Labels: lgtm, approved, needs-ok-to-test

#744 e2e:wait: return updated pod object explicitly
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/9_reboot/devices.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved

#749 e2e: wait for objects deletion
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
Labels: lgtm, approved

#729 OCPBUGS-7980:e2e:ht-aware: exec on the correct worker node
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#752 generate missing files
  docs/performanceprofile/performance_profile.md
  pkg/generated/clientset/versioned/typed/tuned/v1/fake/fake_profile.go
  pkg/generated/clientset/versioned/typed/tuned/v1/fake/fake_tuned.go
Labels: lgtm, approved

#745 OCPBUGS-16908: Release leader election on manager exit
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#754 OCPBUGS-17219: Render mode should not segfault w/ no matching MCP
  pkg/performanceprofile/cmd/render/render.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#751 Makefile: hack: add helpers to compile testsuites
  Makefile
  hack/build-test-bin.sh
  hack/list-test-bin.sh
Labels: lgtm, approved

#756 OCPBUGS-16348: OSLAT latency spikes due to tsc karg setting
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#753 e2e: irqbalance: improve test troubleshooting
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved

#758 OCPBUGS-14026: cgroup: Match the name of the cgroup to what is expected by kubelet
  assets/performanceprofile/scripts/cpuset-configure.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#765 OCPBUGS-17585: Tighten the rules for modifying Tuned Profiles
  assets/tuned/manifests/ds-tuned.yaml
  manifests/20-profile.crd.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#760 [release-4.13] [manual] OCPBUGS-17794: rps: use default rps mask kernel API
  assets/performanceprofile/configs/99-default-rps-mask.conf
  assets/performanceprofile/configs/99-netdev-physical-rps.rules
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#771 Revert "Tighten the rules for modifying Tuned Profiles (#765)"
  assets/tuned/manifests/ds-tuned.yaml
  manifests/20-profile.crd.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-bug

#763 [release-4.13] [manual] OCPBUGS-17845: deflake ht aware test
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#775 OCPBUGS-17585: Tighten the rules for modifying Tuned Profiles
  assets/tuned/manifests/ds-tuned.yaml
  manifests/20-profile.crd.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/operator/status.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/utils/testing/testing.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#767 OCPBUGS-17943: Add rtentsk plugin to pp tuned profile
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
