Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-12, with the labels that each got.

#857 CNF-9264: e2e:latency: omit LatencyTestRun env variable
  docs/performanceprofile/performance_controller.md
  hack/run-test.sh
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, jira/valid-reference

#864 NO-JIRA: Report duplicate profiles as ERRORs
  pkg/manifests/manifests.go
Labels: lgtm, approved, jira/valid-reference

#844 CNF-10238: NTO render command for SNO boot arguments
  cmd/cluster-node-tuning-operator/main.go
  pkg/operator/controller.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
  pkg/performanceprofile/cmd/render/render.go
  pkg/tuned/cmd/render/cmd.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/util/manifests.go
Labels: lgtm, approved, jira/valid-reference

#866 CNF-9664: cpuset-configure: exit gracefully on cgroup v2
  assets/performanceprofile/scripts/cpuset-configure.sh
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-reference

#868 OCPBUGS-24638: Do not set default RPS sysctl twice
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#879 OCPBUGS-24929: Use go 1.21
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#881 NO-JIRA: e2e-test: Call SetLogger to avoid controller-runtime error.
  test/e2e/basic/operator_test.go
Labels: lgtm, approved, jira/valid-reference

#882 NO-JIRA: Fix error logging in metrics server.go
  pkg/metrics/server.go
Labels: lgtm, approved, jira/valid-reference

#871 OCPBUGS-25115: Fix Racing Machine Configs and add Day 0 Support (#854)
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/performanceprofile/controller/performanceprofile/components/manifestset/manifestset.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile_test.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/controller/status.go
  pkg/performanceprofile/node/helper.go
  pkg/performanceprofile/utils/testing/testing.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_node.yaml
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#883 CNF-10676: makefile: add target to trigger mixedcpus e2e test
  Makefile
Labels: lgtm, approved, jira/valid-reference

#875 OCPBUGS-24792: Make MC names deterministic
  pkg/operator/controller.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#877 OCPBUGS-24581: rps: fix mask update for SR-IOV devices
  assets/performanceprofile/configs/99-netdev-physical-rps.rules
  assets/performanceprofile/scripts/set-rps-mask.sh
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#878 CNF-10587: NTO: Fine tuning render bootcmd mc command
  pkg/tuned/cmd/render/cmd.go
  pkg/tuned/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference

#746 OCPBUGS-20368: E2E: Add tests for Dynamic ovs pinning
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#895 OCPBUGS-24581: rps: fail gracefully when mask application failed
  assets/performanceprofile/scripts/set-rps-mask.sh
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
