Repository openshift/cluster-node-tuning-operator, pull requests merged in 2023-04, with the labels that each got.

#602 remove BZ 2181546 from pao e2e skip list
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved

#585 OCPBUGS-10247: Update NTO-generated MC on MachineCount <= 1
  pkg/operator/controller.go
  pkg/operator/mc.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#586 Make the enable-leader-election option work
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved

#600 OCPBUGS-11083: e2e: profile updates tests revised
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#594 render: remove uid from render-sync target
  hack/render-sync.sh
  test/e2e/performanceprofile/testdata/render-expected-output/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved

#592 OCPBUGS-10635: workload-hints: disable stalld when rt disabled
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#581 OCPBUGS-9959: check scheduler settings under /sys/kernel/debug/sched/
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#607 A new env var NO_BZ_CHECKS disables Bz and Jira status checks
  test/e2e/performanceprofile/functests/utils/utils.go
Labels: lgtm, approved

#608 OCPBUGS-11535: tuned: Handle UserLevelNetworking nil pointer gracefully
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#597 OCPBUGS-11125: Backup and revert profile when hugepages test completes
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#611 OCPBUGS-11150: Revert #567 and cleanup PPC-generated TuneD config
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug, jira/valid-reference

#618 [release-4.13] [manual] OCPBUGS-11336: e2e: profile updates tests revised
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#623 OCPBUGS-11914: Remove subPaths, they are broken
  assets/tuned/manifests/ds-tuned.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#617 [release-4.13] OCPNODE-1539: perf profile: add script for preparing cgroups for CPU load balance disabling
  assets/performanceprofile/scripts/cpuset-configure.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#601 OCPNODE-1539: perf profile: add script for preparing cgroups for CPU load balance disabling
  assets/performanceprofile/scripts/cpuset-configure.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, jira/valid-reference

#622 OCPBUGS-12229: e2e: add missing test id
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#639 OCPBUGS-12883: Revert PR558 and PR585 partially
  pkg/operator/controller.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
