Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-06, with the labels that each got.

#1071 NO-JIRA:e2e: latency: Add negative tests
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, jira/valid-reference

#1008 CNF-11815: e2e: Added node inspector for inspecting nodes configuration
  hack/run-test.sh
  test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/9_reboot/devices.go
  test/e2e/performanceprofile/functests/Z_deconfig/Z_deconfig_suite_test.go
  test/e2e/performanceprofile/functests/Z_deconfig/deconfig.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/functests/utils/consts.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
  test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/systemd/systemd.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
  test/e2e/performanceprofile/functests/utils/utils.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1064 OCPBUGS-34720: Add tier0 and tier1 tags to non reboot test cases
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1002 [release-4.14] OCPBUGS-25137: Add a '.snyk' to silence static code analysis warnings
  .snyk
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1073 OCPBUGS-28647: tuned: operand: deferred updates prepare: cleanups from #1019
  Makefile
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
  pkg/operator/profilecalculator_test.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1066 [release-4.15] OCPBUGS-33929: Negative net interface name fix
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1026 CNF-11977: e2e: Added mixed cpus negative tests
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
Labels: lgtm, approved, jira/valid-reference

#1078 NO-JIRA:Dockerfile:bump go-builder to 1.22
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1079 NO-JIRA: remove 4.13->4.14 compatibility code
  cmd/cluster-node-tuning-operator/main.go
Labels: lgtm, approved, jira/valid-reference

#1076 NO-JIRA: e2e:labels: add platform type labels
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference

#1075 OCPBUGS-34972: perfprof: bump verbosiness of logs
  pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
  pkg/performanceprofile/controller/performanceprofile/resources/resources.go
  pkg/performanceprofile/controller/performanceprofile/status/writer.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1091 NO-JIRA: e2e:performance: handle regex failures in tests
  pkg/util/manifests.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-reference

#1092 No-JIRA: e2e:run-test.sh: match ginkgo CLI to ginkgo package
  hack/run-test.sh
Labels: lgtm, approved, jira/valid-reference
