Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-03, with the labels that each got.

#962 NO-JIRA: e2e: testdata: remove the annotated profile
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_annotated.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#976 OCPBUGS-26400: scheduler plugin: ignore IRQs
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#974 NO-JIRA: e2e: perf-prof: increase logging for debugging
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-reference

#872 NO-JIRA: Update OWNERS file
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#969 NO-JIRA: Remove RELEASE_VERSION from test-upstream-tuned.sh
  hack/test-upstream-tuned.sh
Labels: lgtm, approved, jira/valid-reference

#988 NO-JIRA: E2E: skip ovs affinity test due to OCPBUGS-30806
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
Labels: lgtm, approved, jira/valid-reference

#987 OCPBUGS-30812: Ignore scheduler plugin IRQs when globally enabled
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#961 NO-JIRA: e2e:mixedcpus: check env variables of init process
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#994 [release-4.14][manual] OCPBUGS-30980: irqbalance: set banned cpus list to '0'
  assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#995 CNF-11646: makefile:hypershift: initial make target
  Makefile
  hack/show-cluster-version.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#996 OCPBUGS-31042: [release-4.15][manual] hack: fix backport of render-sync.sh
  hack/render-sync.sh
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#940 OCPBUGS-29594: Reduce number of reboots in offline tests
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#980 NO-JIRA: Add sync for rendering extra ctrcfgs
  hack/render-sync.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#998 OCPBUGS-30647: Remove TuneD timeout code and reload on ERRORs
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/tuned/status.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#964 NO-JIRA: Add positive tests with ginkgo timeout
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#967 CNF-11213: added mixedCpus e2e test
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/utils/deployments/deployments.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-reference

#997 NO-JIRA: Remove removePerformanceOLMOperator()
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  go.sum
  pkg/performanceprofile/controller/utils.go
  test/e2e/basic/csvs.go
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/utils/client/clients.go
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/pkg/lib/version/version.go
  vendor/github.com/operator-framework/api/pkg/operators/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/install/install.go
  vendor/github.com/operator-framework/api/pkg/operators/register.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operator_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/operatorgroup_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v1alpha2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1000 OCPBUGS-26162: Fixed .snyk format
  .snyk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1003 [release-4.13] OCPBUGS-31357: irqbalance: set banned cpus list to 0
  assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1005 NO-JIRA: Update tuned profile degraded test
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
Labels: lgtm, approved, jira/valid-reference
