Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-07, with the labels that each got.

#1096 NO-JIRA: hypershift: check updatingConfig condition to be false instead of missing
  test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
Labels: lgtm, approved, jira/valid-reference

#1094 NO-JIRA:pao:hypershift: fix client implementation
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  test/e2e/performanceprofile/functests/utils/client/dataplane.go
Labels: lgtm, approved, jira/valid-reference

#1104 NO-JIRA: Fix requested profile doesn't exist
  hack/dockerfile_install_support.sh
Labels: lgtm, approved, jira/valid-reference

#1105 NO-JIRA: hypershift:unitests: adjust controller unit-tests
  pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/status/writer.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/utils/testing/testing.go
Labels: lgtm, approved, jira/valid-reference

#1095 OCPBUGS-36355: Backport fix for OCPBUGS-30647
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  Makefile
  assets/bin/run
  assets/tuned/manifests/default-cr-tuned.yaml
  assets/tuned/manifests/ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  pkg/manifests/manifests.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/tuned/status.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1093 CNF-13394: Changed node inspector to have lazy initialization
  hack/run-test.sh
  test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
  test/e2e/performanceprofile/functests/10_performance_ppc/10_ppc_suite_test.go
  test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
  test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
  test/e2e/performanceprofile/functests/2_performance_update/test_suite_performance_update_test.go
  test/e2e/performanceprofile/functests/3_performance_status/test_suite_performance_status_test.go
  test/e2e/performanceprofile/functests/4_latency/test_suite_latency_test.go
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/test_suite_mustgather_test.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/test_suite_performance_kubelet_node_test.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/test_suite_performance_workloadhints_test.go
  test/e2e/performanceprofile/functests/9_reboot/test_suite_reboot_test.go
  test/e2e/performanceprofile/functests/Z_deconfig/Z_deconfig_suite_test.go
  test/e2e/performanceprofile/functests/Z_deconfig/deconfig.go
  test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
Labels: lgtm, approved, jira/valid-reference

#1100 CNF-13530: hypershift: support `containerruntimeconfig`
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#1107 NO-JIRA: hypershift: implements missing client calls needed for e2e tests
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
Labels: lgtm, approved, jira/valid-reference

#1097 OCPBUGS-36414: E2E: Add ginkgo labels to all test cases that reboot nodes.
  test/e2e/performanceprofile/functests/10_performance_ppc/ppc.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/3_performance_status/status.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/9_reboot/devices.go
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1090 NO-JIRA: Rename and reorganize hypershift labels
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/consts/consts.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-reference

#1084 CNF-7123: Enable and adjust 1_performance suite on Hypershift
  Makefile
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
  test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
  test/e2e/performanceprofile/functests/3_performance_status/status.go
  test/e2e/performanceprofile/functests/utils/client/clients.go
  test/e2e/performanceprofile/functests/utils/cluster/cluster.go
  test/e2e/performanceprofile/functests/utils/discovery/discovery.go
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
  test/e2e/performanceprofile/functests/utils/profilesupdate/profile_update.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1106 NO-JIRA: e2e: performance: verify tuned one-shot service vs kubelet
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1111 NO-JIRA: e2e: performance: skip test on env with insufficient cpus
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1116 NO-JIRA: makefile: ensure bindata
  Makefile
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1112 NO-JIRA: Fix the destination of asset's copy
  hack/dockerfile_install_support.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1110 OCPBUGS-36870: Remove tuned/rendered object
  manifests/20-profile.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/generated/informers/externalversions/factory.go
  pkg/manifests/manifests.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/profilecalculator.go
  pkg/operator/profilecalculator_test.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1119 OCPBUGS-28647: deferred updates: cleanups
  Makefile
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  test/e2e/deferred/basic.go
  test/e2e/deferred/non_regression.go
  test/e2e/deferred/restart.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1089 CNF-12680:CNF-13488: Add performance profile status for hypershift support
  Makefile
  cmd/cluster-node-tuning-operator/main.go
  go.mod
  pkg/operator/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/consts/consts.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift_test.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/status/status.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/status/writer.go
  pkg/performanceprofile/controller/performanceprofile/status/status.go
  pkg/performanceprofile/controller/performanceprofile/status/writer.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/3_performance_status/status.go
  test/e2e/performanceprofile/functests/3_performance_status/test_suite_performance_status_test.go
  test/e2e/performanceprofile/functests/utils/client/dataplane.go
  test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
  vendor/github.com/onsi/gomega/gcustom/make_matcher.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1120 NO-JIRA: Project cleanups
  Dockerfile.rhel8
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  assets/tuned/manifests/ds-tuned.yaml
  hack/dockerfile_install_support.sh
  pkg/apis/tuned/v1/tuned_types.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
  version/version.go
Labels: lgtm, approved, jira/valid-reference

#1115 CNF-12711: hypershift: enable feature gate support
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/performanceprofile/components/components.go
  pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-reference

#1108 CNF-13530: controller: predicate for `containerruntimeconfig`
  pkg/operator/hypershift.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-reference

#1117 [release-4.15] OCPBUGS-37306: set required-scc for openshift workloads
  assets/tuned/manifests/ds-tuned.yaml
  manifests/50-operator-ibm-cloud-managed.yaml
  manifests/50-operator.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1121 NO-JIRA:e2e:hypershift: remove/rename deprecated env variables
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/utils/hypershift/hypershift.go
Labels: lgtm, approved, jira/valid-reference
