Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-08, with the labels that each got.

#1125 OCPBUGS-36868: TuneD prior to kubelet in one-shot mode
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  pkg/metrics/server.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/util/os.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1122 NO-JIRA:e2e:document: how to run locally on HCP platform
  test/e2e/performanceprofile/functests/README.md
Labels: lgtm, approved, jira/valid-reference

#1123 OCPBUGS-37865: E2E: Verify ovs threadpool inherits parent cpu affinity
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1132 OCPBUGS-34917: Operator: do not use /tmp
  pkg/metrics/server.go
  pkg/operator/controller.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1126 OCPBUGS-37734: Backport fix for OCPBUGS-36355
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  Makefile
  assets/bin/run
  assets/tuned/manifests/default-cr-tuned.yaml
  assets/tuned/manifests/ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  pkg/manifests/manifests.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/tuned/status.go
  version/version.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1129 OCPBUGS-28647: tuned: distinguish deferred updates
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
  pkg/tuned/controller.go
  pkg/tuned/controller_test.go
  pkg/util/annotations.go
  pkg/util/annotations_test.go
  test/e2e/deferred/basic.go
  test/e2e/deferred/non_regression.go
  test/e2e/deferred/operator_test.go
  test/e2e/deferred/restart.go
  test/e2e/deferred/updates.go
  test/e2e/testing_manifests/deferred/tuned-basic-updates-00.yaml
  test/e2e/testing_manifests/deferred/tuned-basic-updates-10.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1059 NO-JIRA: Remove vestiges of annotation ignore-cgroups-version from tests
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
Labels: lgtm, approved, jira/valid-reference

#1136 PSAP-1428: Read-only filesystem for the operator
  manifests/50-operator-ibm-cloud-managed.yaml
  manifests/50-operator.yaml
Labels: lgtm, approved, jira/valid-reference

#1133 OCPBUGS-37754: Remove tuned/rendered object
  manifests/20-profile.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/manifests/manifests.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/profilecalculator.go
  pkg/operator/profilecalculator_test.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1137 OCPBUGS-38629: TuneD prior to kubelet in one-shot mode
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  pkg/metrics/server.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/util/os.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1139 CNF-13014: Allow specifying $TAG separately from the full image path
  HACKING.md
  Makefile
  hack/deploy-custom-nto.sh
Labels: lgtm, approved, jira/valid-reference

#1114 PSAP-1471: Add support for setting operand verbosity
  manifests/20-profile.crd.yaml
  manifests/20-tuned.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
  pkg/tuned/controller.go
  pkg/util/log.go
Labels: lgtm, approved, jira/valid-reference

#1140 NO-JIRA:E2E: Remove checking of reserved cpus in irqbalance file
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-reference

#1142 OCPBUGS-38795: Fix defer status during recommended profile change
  pkg/tuned/controller.go
  test/e2e/deferred/basic.go
  test/e2e/deferred/operator_test.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1127 OCPBUGS-37956: E2E: Add test to verify cpuset.cpus.exclusive is writeable
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1144 OCPBUGS-39005: Add cluster-wide proxy env file
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1131 OCPBUGS-36431: Fix generated cpu mask for 512+ cpus
  pkg/performanceprofile/controller/performanceprofile/components/utils.go
  pkg/performanceprofile/controller/performanceprofile/components/utils_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1060 NO-JIRA: E2E: Remove explicitly setting Realtime kernel and realtime hint
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved, jira/valid-reference

#1143 CNF-13756: Adjust mustgather test suite for hypershift
  Makefile
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
Labels: lgtm, approved, jira/valid-reference

#1069 OCPBUGS-34486: release-4.13 [manual] workload hints test fixes
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference
