Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-11, with the labels that each got.

#1200 OCPBUGS-43992: e2e: wait for node inspector deletion
  test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1204 OCPBUGS-44180: Unblock 4.16 CI
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1206 NO-JIRA: nodeInspector: do not reuse namespace
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
  test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
Labels: lgtm, approved, jira/valid-reference

#1208 OCPBUGS-44283: right-hand-side profile_dirs take precedence
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1099 PSAP-1428: read only root filesystem
  Dockerfile
  Dockerfile.rhel9
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  assets/tuned/manifests/ds-tuned.yaml
  hack/dockerfile_install_support.sh
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-reference

#1172 NO-JIRA: Drop GOOS=linux from Makefile
  Makefile
Labels: lgtm, approved, jira/valid-reference

#1214 OCPBUGS-44477: Fix nil pointer dereference caused by external calling of validation function
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1207 OCPBUGS-44275: Drop sched_migration_cost_ns setting
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/generated/informers/externalversions/factory.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1215 OCPBUGS-44506: Drop sched_migration_cost_ns setting
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1213 OCPBUGS-44372: PPC: skip comparing ProcessorCore.Index between NUMA cores
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1150 OCPBUGS-39333: E2E: Add support for hypershift to ovs dynamic pinning and kubelet.experimental annotation tests
  Makefile
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/test_suite_performance_kubelet_node_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1184 OCPBUGS-43832: E2E: Add tests to support NTO over hypershift with multi nodepools.
  Makefile
  test/e2e/performanceprofile/functests/12_hypershift/12_hypershift_suite_test.go
  test/e2e/performanceprofile/functests/12_hypershift/hypershift.go
  test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1222 NO-JIRA: Fix upstream and OKD builds
  hack/dockerfile_install_support.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1223 NO-JIRA: PPC: fix error message
  pkg/performanceprofile/profilecreator/profilecreator.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1224 OCPBUGS-45048: Move reboot tests to appropriate make target for hypershift
  Makefile
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
