Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-09, with the labels that each got.

#1156 [release-4.16] OCPBUGS-39528: E2E: Remove checking of reserved cpus in irqbalance file
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1158 OCPBUGS-41329: E2E: wait for ovs services affinity to reset after deployment deletion
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1159 OCPBUGS-41995: Fixing empty tuned submodule when using Dockerfile
  Dockerfile
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1162 NO-JIRA: deferred updates: fix in-place update handling on reboot
  pkg/tuned/controller.go
  test/e2e/deferred/basic.go
  test/e2e/deferred/non_regression.go
  test/e2e/deferred/operator_test.go
  test/e2e/deferred/restart.go
  test/e2e/deferred/updates.go
  test/e2e/testing_manifests/deferred/tuned-basic-00.yaml
  test/e2e/testing_manifests/deferred/tuned-basic-10.yaml
  test/e2e/testing_manifests/deferred/tuned-basic-20.yaml
  test/e2e/testing_manifests/deferred/tuned-basic-updates-00.yaml
  test/e2e/testing_manifests/deferred/tuned-basic-updates-10.yaml
Labels: lgtm, approved, jira/valid-reference

#1161 OCPBUGS-41486: E2E: Add support for hypershift to memory manager
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1168 CNF-14557:hypershift: make target for perf profile update suites
  Makefile
Labels: lgtm, approved, jira/valid-reference

#1167 NO-JIRA: Add a script to test internal TuneD FDP releases
  HACKING.md
  Makefile
  hack/deploy-custom-nto.sh
  hack/test-tuned-fdp.sh
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-reference

#1171 OCPBUGS-42284: Add cluster-wide proxy env file
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1175 NO-JIRA: Fix failing pao-functests after a MCO change
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-reference

#1174 NO-JIRA: Fix context deadlines in ExecCommandOnPod()
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-reference
