Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-02, with the labels that each got.

#932 CNF-11145: Enhance render sync to include bootstrap rendering tests
  hack/render-sync.sh
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_annotated.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-reference

#933 CNF-11091: Change webhook failure policy to ignore
  manifests/45-webhook-configuration.yaml
Labels: lgtm, approved, jira/valid-reference

#909 NO-JIRA: e2e: set performance profile cpus using env vars
  test/e2e/performanceprofile/functests/0_config/config.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/README.md
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#928 OCPBUGS-27948: Tuned rendering and MCP detection improvements
  hack/render-sync.sh
  pkg/performanceprofile/cmd/render/render.go
  pkg/tuned/cmd/render/cmd.go
  pkg/tuned/cmd/render/render.go
  pkg/util/manifests.go
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/extra-mcp/machine_config_pool.yaml
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/performance/pao_master.yaml
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/performance/pao_worker.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-worker-cnf-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#906 CNF-9173: e2e: cgroups: introduce cgroup package
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/utils/cgroup/cgroup.go
  test/e2e/performanceprofile/functests/utils/cgroup/controller/controller.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-reference

#938 NO-JIRA: Bump TuneD to the latest OCP-shipped TuneD upstream version
  Makefile
  assets/tuned/daemon/com.redhat.tuned.policy
  assets/tuned/daemon/man/tuned-adm.8
  assets/tuned/daemon/profiles/cpu-partitioning/tuned.conf
  assets/tuned/daemon/profiles/functions
  assets/tuned/daemon/profiles/network-latency/tuned.conf
  assets/tuned/daemon/profiles/realtime-virtual-guest/tuned.conf
  assets/tuned/daemon/profiles/realtime-virtual-host/tuned.conf
  assets/tuned/daemon/profiles/realtime/tuned.conf
  assets/tuned/daemon/tests/beakerlib/Program-tuned-tried-to-access-dev-mem-between/main.fmf
  assets/tuned/daemon/tests/beakerlib/Program-tuned-tried-to-access-dev-mem-between/runtest.sh
  assets/tuned/daemon/tests/beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/main.fmf
  assets/tuned/daemon/tests/beakerlib/Tuned-takes-too-long-to-reload-start-when-ulimit/runtest.sh
  assets/tuned/daemon/tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/main.fmf
  assets/tuned/daemon/tests/beakerlib/bz1798183-RFE-support-post-loaded-profile/runtest.sh
  assets/tuned/daemon/tests/beakerlib/error-messages/main.fmf
  assets/tuned/daemon/tests/beakerlib/error-messages/runtest.sh
  assets/tuned/daemon/tests/beakerlib/tuned-adm-functionality/main.fmf
  assets/tuned/daemon/tests/beakerlib/tuned-adm-functionality/runtest.sh
  assets/tuned/daemon/tests/beakerlib/variables-support-in-profiles/runtest.sh
  assets/tuned/daemon/tests/unit/plugins/test_base.py
  assets/tuned/daemon/tuned-adm.py
  assets/tuned/daemon/tuned-gui.glade
  assets/tuned/daemon/tuned-gui.py
  assets/tuned/daemon/tuned.spec
  assets/tuned/daemon/tuned/admin/admin.py
  assets/tuned/daemon/tuned/admin/dbus_controller.py
  assets/tuned/daemon/tuned/consts.py
  assets/tuned/daemon/tuned/daemon/application.py
  assets/tuned/daemon/tuned/daemon/controller.py
  assets/tuned/daemon/tuned/daemon/daemon.py
  assets/tuned/daemon/tuned/gtk/gui_plugin_loader.py
  assets/tuned/daemon/tuned/plugins/base.py
  assets/tuned/daemon/tuned/plugins/hotplug.py
  assets/tuned/daemon/tuned/plugins/instance/instance.py
  assets/tuned/daemon/tuned/plugins/plugin_audio.py
  assets/tuned/daemon/tuned/plugins/plugin_bootloader.py
  assets/tuned/daemon/tuned/plugins/plugin_cpu.py
  assets/tuned/daemon/tuned/plugins/plugin_disk.py
  assets/tuned/daemon/tuned/plugins/plugin_modules.py
  assets/tuned/daemon/tuned/plugins/plugin_net.py
  assets/tuned/daemon/tuned/plugins/plugin_scheduler.py
  assets/tuned/daemon/tuned/plugins/plugin_script.py
  assets/tuned/daemon/tuned/plugins/plugin_scsi_host.py
  assets/tuned/daemon/tuned/plugins/plugin_selinux.py
  assets/tuned/daemon/tuned/plugins/plugin_service.py
  assets/tuned/daemon/tuned/plugins/plugin_sysctl.py
  assets/tuned/daemon/tuned/plugins/plugin_sysfs.py
  assets/tuned/daemon/tuned/plugins/plugin_systemd.py
  assets/tuned/daemon/tuned/plugins/plugin_usb.py
  assets/tuned/daemon/tuned/plugins/plugin_video.py
  assets/tuned/daemon/tuned/plugins/plugin_vm.py
  assets/tuned/daemon/tuned/profiles/functions/function_calc_isolated_cores.py
  assets/tuned/daemon/tuned/profiles/functions/functions.py
  assets/tuned/daemon/tuned/units/manager.py
  assets/tuned/daemon/tuned/utils/commands.py
  assets/tuned/daemon/tuned/utils/config_parser.py
  assets/tuned/daemon/tuned/utils/nettool.py
  assets/tuned/daemon/tuned/version.py
Labels: lgtm, approved, jira/valid-reference

#936 NO-JIRA: e2e: classifying tests using labels
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference

#939 NO-JIRA: Fix e2e tests on SNO
  test/e2e/testing_manifests/sno/kernel_parameter_add_rm-child.yaml
  test/e2e/testing_manifests/sno/kernel_parameter_add_rm-parent.yaml
  test/e2e/testing_manifests/sno/stalld-disable.yaml
  test/e2e/testing_manifests/sno/stalld.yaml
Labels: lgtm, approved, jira/valid-reference

#937 OCPBUGS-29183: Enable crun as runtime only if missing
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#944 NO-JIRA: skip realtime disabled tests due to OCPBUGS-28828
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/valid-reference

#947 NO-JIRA: e2e: fix typo in label name
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference

#892 CNF-9173: e2e: mixedcpus test
  test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
Labels: lgtm, approved, jira/valid-reference

#951 NO-JIRA: render: perfprofile: don't annotate perfprof
  pkg/performanceprofile/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference

#942 [release-4.15] [manual] OCPBUGS-29376: e2e: cgroups: introduce cgroup package
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/utils/cgroup/cgroup.go
  test/e2e/performanceprofile/functests/utils/cgroup/controller/controller.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#949 [release-4.15][manual] OCPBUGS-29396: Labels for e2e testing
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#953 [release-4.15][manual] OCPBUGS-27227: irqbalance: set banned cpus list to '0'
  assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#912 CNF-9173: e2e: mixedcpus: kubelet restart test
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, jira/valid-reference

#956 OCPBUGS-22095: Render: Add MCSelector to missing default MCPs
  pkg/util/manifests.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#957 OCPBUGS-29594: e2e: fix comparing incompatible types
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#952 [release-4.15][manual] OCPBUGS-29376: Mixed CPUs e2e tests
  test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#960 NO-JIRA: Add support to inject owner-ref argument to render command
  hack/render-sync.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#954 OCPBUGS-23167: Add performance real time tuned template
  assets/performanceprofile/tuned/openshift-node-performance
  assets/performanceprofile/tuned/openshift-node-performance-rt
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile/components/consts.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#935 CNF-10170: Avoid command to fail if there is no PP on input folders
  assets/tuned/assets.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-reference

#970 Jira PSAP-1288: NTO operand cleanup
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  Makefile
  assets/bin/run
  assets/tuned/manifests/default-cr-tuned.yaml
  assets/tuned/manifests/ds-tuned.yaml
  cmd/cluster-node-tuning-operator/main.go
  pkg/manifests/manifests.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
Labels: lgtm, approved, jira/valid-reference

#972 OCPBUGS-29641: fix rendering extra ctrcfgs
  pkg/performanceprofile/cmd/render/render.go
  test/e2e/performanceprofile/cluster-setup/container-runtime-crun/enable-crun-master.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
