Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-10, with the labels that each got.

#1169 NO-JIRA: hypershift:handler: add KubeletConfig unique label
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler_test.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/consts/consts.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#1153 [release-4.16] OCPBUGS-39379: E2E: Add test to verify cpuset.cpus.exclusive is writeable
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1176 OCPBUGS-42567: Add cluster-wide proxy env file
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1182 NO-JIRA: CI: unblock
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-reference

#1163 OCPBUGS-38900: Drop sched_migration_cost_ns setting
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1177 OCPBUGS-42492: Make ocp-tuned-one-shot.service restart on-failure
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1151 NO-JIRA: Remove upstream TuneD patch
  assets/tuned/patches/030-no-bootloader-errors.diff
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-reference

#1185 No-Jira: E2E: fix modify node selector to use lowercase
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-reference

#1181 NO-JIRA: logs: avoid spamming when PerformanceProfile is missing
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-reference

#1190 NO-JIRA: Default to username and timestamp for custom NTO push
  hack/deploy-custom-nto.sh
Labels: lgtm, approved, jira/valid-reference

#1196 PSAP-1567: Fix linter warnings
  pkg/operator/controller.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-reference

#1199 NO-JIRA: Fix typo in codegen script
  hack/update-codegen.sh
Labels: lgtm, approved, jira/valid-reference

#1198 OCPBUGS-43665: Drop amd_iommu=on from amd tuning
  assets/performanceprofile/tuned/openshift-node-performance-amd-x86
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1197 OCPBUGS-43666: Fix kernel arguments ordering on Intel
  assets/performanceprofile/tuned/openshift-node-performance
  assets/performanceprofile/tuned/openshift-node-performance-intel-x86
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1194 CNF-13014: Align dockerfile ocp version
  Dockerfile
Labels: lgtm, approved, jira/valid-reference
