Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-01, with the labels that each got.

#903 OCPBUGS-25595: Make MC names deterministic
  pkg/operator/controller.go
  pkg/operator/mc.go
  pkg/operator/profilecalculator.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#899 OCPBUGS-25699: irqbalance: set banned cpus list to '0'
  assets/performanceprofile/scripts/clear-irqbalance-banned-cpus.sh
  pkg/performanceprofile/controller/performanceprofile/components/assets_scripts_test.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#902 OCPBUGS-26162: Add .snyk file for static code analysis
  .snyk
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#917 NO-JIRA: skip crun configuration test
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-reference

#898 CNF-10786:e2e: general improvements and cleanup
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/basic/available.go
  test/e2e/basic/csvs.go
  test/e2e/basic/metrics_cert_rotation.go
  test/e2e/basic/netdev_set_channels.go
  test/e2e/basic/profile_status.go
  test/e2e/basic/rollback.go
  test/e2e/basic/sysctl_d_override.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/1_performance/rt-kernel.go
  test/e2e/performanceprofile/functests/1_performance/topology_manager.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/4_latency/latency.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/9_reboot/devices.go
  test/e2e/performanceprofile/functests/utils/daemonset/daemonset.go
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  test/e2e/performanceprofile/functests/utils/namespaces/namespaces.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
  test/e2e/util/util.go
Labels: lgtm, approved, jira/valid-reference

#910 NO-JIRA: HyperShift code linter PR837 followup
  pkg/operator/controller.go
  pkg/operator/hypershift.go
Labels: lgtm, approved, jira/valid-reference

#920 NO-JIRA: README Doc Typo Fix
  README.md
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#913 [release-4.14] OCPBUGS-26597: E2E: Add tests for Dynamic ovs pinning …
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#833 OCPBUGS-22095: Add default MCP objects for rendering
  pkg/performanceprofile/cmd/render/render.go
  pkg/tuned/cmd/render/render.go
  pkg/util/manifests.go
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/extra-mcp/machine_config_pool.yaml
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/performance/pao_master.yaml
  test/e2e/performanceprofile/cluster-setup/bootstrap-cluster/performance/pao_worker.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-worker-cnf-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#911 NO-JIRA: e2e: log: set ctrl-runtime logger
  test/e2e/performanceprofile/functests/0_config/test_suite_performance_config_test.go
  test/e2e/performanceprofile/functests/1_performance/test_suite_performance_test.go
  test/e2e/performanceprofile/functests/2_performance_update/test_suite_performance_update_test.go
  test/e2e/performanceprofile/functests/3_performance_status/test_suite_performance_status_test.go
  test/e2e/performanceprofile/functests/4_latency/test_suite_latency_test.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/test_suite_mustgather_test.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/test_suite_performance_kubelet_node_test.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/test_suite_performance_workloadhints_test.go
  test/e2e/performanceprofile/functests/9_reboot/test_suite_reboot_test.go
Labels: lgtm, approved, jira/valid-reference

#916 CNF-6517: Export ValidateBasicFields for Hypershift
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, jira/valid-reference

#929 NO-JIRA: Skip PerformanceProfile update test
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
Labels: lgtm, approved, jira/valid-reference

#914 NO-JIRA:e2e: `UpdateWithRetry` only update spec
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#890 OCPBUGS-24636: Report duplicate priority only for multiple matching profiles
  pkg/operator/profilecalculator.go
Labels: lgtm, approved, ok-to-test, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#924 CNF-10170: Render MC without additional PP
  pkg/tuned/cmd/render/render.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#918 Revert "NO-JIRA: skip crun configuration test"
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
