Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-04, with the labels that each got.

#948 OCPBUGS-29183: e2e: when crun is enabled by default skip checking runc config
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#991 NO-JIRA: E2E: Add systemd package to fetch properties of cgroup slice
  test/e2e/performanceprofile/functests/utils/cgroup/cgroup.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/systemd/systemd.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#992 OCPBUGS-30569: Systemd processes not being moved to cpuset/systemd.slice fix
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#984 [release-4.15] [manual] OCPBUGS-30507: Add performance real time tuned template
  assets/performanceprofile/tuned/openshift-node-performance
  assets/performanceprofile/tuned/openshift-node-performance-rt
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile/components/consts.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#983 [release-4.15] OCPBUGS-30306: scheduler plugin: ignore IRQs
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#993 NO-JIRA: E2E: Adjust tests for cgroupv2 changes
  test/e2e/performanceprofile/functests/1_performance/hugepages.go
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/valid-reference

#955 OCPBUGS-29596: e2e: Enhance tests related to crio annotations
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/utils/cgroup/controller/controller.go
  test/e2e/performanceprofile/functests/utils/cgroup/v1/v1.go
  test/e2e/performanceprofile/functests/utils/cgroup/v2/v2.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1016 OCPBUGS-31692: [release-4.15] [manual]: Systemd processes not being moved to cpuset/systemd.slice fix
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1023 [release-4.14] OCPBUGS-31844: Scheduler plugin: ignore IRQs
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1011 NO-JIRA: E2E: Adjust Dynamic ovs pinning tests with cgroupv2
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
Labels: lgtm, approved, jira/valid-reference

#1010 CNF-10873: set Cgroups V2 as default
  manifests/40-rbac.yaml
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/performanceprofile/controller/performanceprofile/components/manifestset/manifestset.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile_test.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/controller/status.go
  pkg/performanceprofile/node/helper.go
  pkg/performanceprofile/utils/testing/testing.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-reference

#1027 [release-4.13] OCPBUGS-31936: Scheduler plugin: ignore IRQs
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1033 NO-JIRA: E2E: Update the awk print field to fetch rhcos-image
  test/e2e/performanceprofile/functests/1_performance/performance.go
Labels: lgtm, approved, jira/valid-reference

#1031 NO-JIRA: E2E: use strings.CutPrefix instead of trim function to get containerID
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, jira/valid-reference

#1014 OCPBUGS-31690: [manual][release-4.15] E2E: Reduce number of reboots in offline tests
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1024 OCPBUGS-30647: NTO operand (openshift-tuned) fixes
  pkg/tuned/controller.go
  pkg/tuned/run.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1012 OCPBUGS-31694: E2E: Workload hints test cases fixes
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1034 [release-4.12] OCPBUGS-32205: Scheduler plugin: ignore IRQs
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1018 OCPBUGS-31735: [release-4.14] [manual]: Report duplicate priority only for multiple matching profiles
  pkg/operator/profilecalculator.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1025 OCPBUGS-31905: [release-4.14] [manual] : Add performance real time tuned template
  assets/performanceprofile/tuned/openshift-node-performance
  assets/performanceprofile/tuned/openshift-node-performance-rt
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile/components/consts.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1038 [release-4.12] OCPBUGS-31442: Refactor IRQ load balancing enable/disable test
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1039 NO-JIRA: pao:controller: remove depracated function
  pkg/performanceprofile/controller/performanceprofile_controller.go
Labels: lgtm, approved, jira/valid-reference

#1041 CNF-11985: Enhance latency cnf-tests UX
  test/e2e/performanceprofile/functests/4_latency/latency.go
Labels: lgtm, approved, jira/valid-reference

#973 OCPBUGS-30111: Negative net interface name does not reduce queues
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1030 PSAP-1354: Updated a script for deploying a custom NTO image to a cluster
  Dockerfile
  HACKING.md
  hack/deploy-custom-nto.sh
Labels: lgtm, approved, jira/valid-reference

#1032 CNF-6517: [Part 1] Hypershift PAO adoption
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/resources/resources.go
  pkg/performanceprofile/controller/performanceprofile/status/status.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/mcps/mcps.go
Labels: lgtm, approved, jira/valid-reference

#1036 OCPBUGS-32469: Remove tuned/rendered object
  manifests/20-profile.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/generated/informers/externalversions/factory.go
  pkg/manifests/manifests.go
  pkg/operator/controller.go
  pkg/operator/hypershift.go
  pkg/operator/profilecalculator.go
  pkg/operator/profilecalculator_test.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  test/e2e/performanceprofile/functests/6_mustgather_testing/mustgather.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#950 CNF-11099: set intel_pstate driver to automatic as default
  assets/performanceprofile/tuned/openshift-node-performance
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/utils/tuned/tuned.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#1037 CNF-6517: [Part 2] Hypershift PAO adoption
  cmd/cluster-node-tuning-operator/main.go
  pkg/performanceprofile/controller/performanceprofile/components/components.go
  pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
  pkg/performanceprofile/controller/performanceprofile/resources/resources.go
  pkg/performanceprofile/controller/performanceprofile/status/status.go
  pkg/performanceprofile/controller/performanceprofile/status/writer.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#1047 NO-JIRA: perfprof: e2e: account for node base load
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-reference

#1045 OCPBUGS-26401: TuneD prior to kubelet in one-shot mode
  Dockerfile
  Dockerfile.rhel8
  Dockerfile.rhel9
  assets/performanceprofile/configs/ocp-tuned-one-shot.service
  pkg/metrics/server.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/tuned/cmd/operand/cmd.go
  pkg/tuned/cmd/render/render.go
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/util/os.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1043 OCPBUGS-32699: E2E: [manual] [release-4.15] Workload hints test cases fixes
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#968 AUTH-482: set required-scc for openshift workloads
  assets/tuned/manifests/ds-tuned.yaml
  manifests/50-operator-ibm-cloud-managed.yaml
  manifests/50-operator.yaml
Labels: lgtm, approved, jira/valid-reference
