Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-05, with the labels that each got.

#1049 OCPBUGS-32978: fix extra-reboot on upgrade with paused mcp worker
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/utils/testing/testing.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1044 NO-JIRA: perfprof: latency e2e: adjust failure message
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, jira/valid-reference

#1053 OCPBUGS-32980: [release-4.14]:fix extra-reboot on upgrade with paused mcp worker
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/performanceprofile/controller/resources.go
  pkg/performanceprofile/utils/testing/testing.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1050 OCPBUGS-33112: E2E: Add automation to check default cpuset from cpu manager state file
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1056 NO-JIRA: E2E: modify test use HaveKey matchter instead of ContainElement
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
Labels: lgtm, approved, jira/valid-reference

#1055 OCPBUGS-33460: E2E: change tuned profile path
  test/e2e/performanceprofile/functests/1_performance/netqueues.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#978 [release-4.14] OCPBUGS-30153: fix rendering extra ctrcfgs
  hack/render-sync.sh
  pkg/performanceprofile/cmd/render/render.go
  test/e2e/performanceprofile/cluster-setup/container-runtime-crun/enable-crun-worker-cnf.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1004 CNF-11817: e2e: control and data planes clients
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  test/e2e/performanceprofile/functests/utils/client/clients.go
  test/e2e/performanceprofile/functests/utils/client/dataplane.go
  test/e2e/performanceprofile/functests/utils/hypershift/hypershift.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1048 OCPBUGS-33030: [release-4.13][manual]Reduce number of reboots in offline tests
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1046 NO-JIRA: E2E: Add test for checking cpuset.cpus.exclusive
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1028 No-Jira: E2E: Extend mixed cpus tests to test cpu load balancing annotation
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1001 [release-4.15] OCPBUGS-28368: Add a '.snyk' to silence static code analysis warnings
  .snyk
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1070 NO-JIRA: E2E: Fetch pod node instead of relying on first worker-cnf node
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-reference

#926 CNF-10616: e2e: Added hwlatdetect default window size
  test/e2e/performanceprofile/functests/5_latency_testing/latency_testing.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference
