Repository openshift/cluster-node-tuning-operator, pull requests merged in 2024-12, with the labels that each got.

#1219 CNF-15505: Remove container runtime selection
  assets/performanceprofile/configs/99-runtimes.conf
  hack/render-sync.sh
  manifests/40-rbac.yaml
  pkg/operator/hypershift.go
  pkg/performanceprofile/cmd/render/render.go
  pkg/performanceprofile/controller/performanceprofile/components/components.go
  pkg/performanceprofile/controller/performanceprofile/components/handler/handler.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/components/handler.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/consts/consts.go
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  pkg/performanceprofile/controller/performanceprofile/status/status.go
  pkg/performanceprofile/controller/performanceprofile_controller.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/cluster-setup/container-runtime-crun/enable-crun-master.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/cgroup/runtime/runtime.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-master-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/01_01-worker-cpu-partitioning_workload_pinning_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_machineconfig.yaml
Labels: lgtm, approved, jira/valid-reference

#1232 OCPBUGS-45264: Normalize cpu sets when rendering to Tuned profiles
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1231 OCPBUGS-45346: performanceprofile cpuset input validation
  Makefile
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1236 OCPBUGS-44372: cmd: PPC: support tolerating heterogeneous core IDs
  cmd/performance-profile-creator/cmd/root.go
  pkg/performanceprofile/profilecreator/helper.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1246 OCPBUGS-45971: e2e: tuned degraded test fix
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1248 [release-4.17] OCPBUGS-45627: Normalize cpu sets when rendering to Tuned profiles
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1252 [release-4.17] OCPBUGS-44644: cmd: PPC: support tolerating heterogeneous core IDs
  cmd/performance-profile-creator/cmd/root.go
  pkg/performanceprofile/profilecreator/helper.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1191 [release-4.17] OCPBUGS-43664: Add vendor and architecture specific tuning options
  assets/performanceprofile/tuned/openshift-node-performance
  assets/performanceprofile/tuned/openshift-node-performance-amd-x86
  assets/performanceprofile/tuned/openshift-node-performance-arm-aarch64
  assets/performanceprofile/tuned/openshift-node-performance-intel-x86
  pkg/performanceprofile/controller/performanceprofile/components/consts.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned.go
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-ctrcfg/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1249 OCPBUGS-46426: e2e: add irdma to module_blacklist kernel args
  test/e2e/performanceprofile/functests/0_config/config.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1256 NO-JIRA:e2e:labels: fix typo and adding type
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference

#1255 NO-JIRA: e2e: common way to fetch poolName
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/utils/poolname/poolname.go
Labels: lgtm, approved, jira/valid-reference

#1229 CNF-16063: E2E: Add hypershift support to container runtime config tests
  pkg/performanceprofile/controller/performanceprofile/hypershift/hypershift.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/nodepools/nodepools.go
Labels: lgtm, approved, jira/valid-reference

#1260 NO-JIRA: Update OWNERS file
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#1173 OCPBUGS-42365: E2E: Adjusted mixed_cpus suite for hypershift
  test/e2e/performanceprofile/functests/11_mixedcpus/11_mixedcpus_suite_test.go
  test/e2e/performanceprofile/functests/11_mixedcpus/mixedcpus.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1230 CNF-15494: E2E: Tuned deferred test automation
  test/e2e/performanceprofile/functests/2_performance_update/tuned_deferred.go
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1263 OCPBUGS-47658: [release-4.16][manual]: Fix context deadlines in ExecCommandOnPod()
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
