Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-02, with the labels that each got.

#1291 OCPBUGS-49403: E2E: Add configuration tests related to align cpus by uncorecache feature
  Makefile
  test/e2e/performanceprofile/functests/13_llc/llc.go
  test/e2e/performanceprofile/functests/13_llc/test_suite_llc_test.go
  test/e2e/performanceprofile/functests/utils/profiles/profiles.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1294 OCPBUGS-49823: Support hugepage size selection for ARM-based clusters
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/kustomization.yaml
  test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/performance_profile.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1088 OCPBUGS-35911: E2E: Add test to verify runc process excludes the cpus used by pod.
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1295 OCPBUGS-49823: machineconfig: add support for various hugepage sizes
  go.mod
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1296 CNF-16742: kernelPageSize + hugepages combinations validation
  docs/performanceprofile/performance_profile.md
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, jira/valid-reference

#1300 OCPBUGS-51314: release-4.18: [manual] e2e: common way to fetch poolName (#1255)
  test/e2e/performanceprofile/functests/2_performance_update/memorymanager.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/kubelet.go
  test/e2e/performanceprofile/functests/utils/poolname/poolname.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
