Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-06, with the labels that each got.

#1332 OCPBUGS-56902: fix: stop referencing non existing git references in go.mod
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1329 NO-JIRA: Update performance_profile.md
  docs/performanceprofile/performance_profile.md
Labels: lgtm, approved, jira/valid-reference

#1327 NO-JIRA: Change /master to /control-plane node label
  README.md
  assets/tuned/manifests/default-cr-tuned.yaml
  manifests/50-operator.yaml
  test/e2e/testing_manifests/csv-dummy.yaml
  test/e2e/util/util.go
Labels: lgtm, approved, jira/valid-reference

#1325 NO-JIRA: Set minimum TLS 1.3 for metrics and webhook servers
  cmd/cluster-node-tuning-operator/main.go
  pkg/metrics/server.go
Labels: lgtm, approved, jira/valid-reference

#1308 OCPBUGS-57520: e2e: llc: initial tests for cpu allocation
  test/e2e/performanceprofile/functests/13_llc/llc.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1341 [release-4.18] OCPBUGS-57947: CNF-18142: Add kernel page size field [1/3]
  docs/performanceprofile/performance_profile.md
  manifests/20-performance-profile.crd.yaml
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
  pkg/apis/performanceprofile/v2/zz_generated.deepcopy.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1342 [release-4.18]: OCPBUGS-57947: Support hugepage size selection for ARM-based clusters [2/3]
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/kustomization.yaml
  test/e2e/performanceprofile/cluster-setup/manual-cluster/arm/performance_profile.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_runtimeclass.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1343 [release-4.18]: OCPBUGS-57947: kernelPageSize + hugepages combinations validation [3/3]
  docs/performanceprofile/performance_profile.md
  pkg/apis/performanceprofile/v2/performanceprofile_types.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation.go
  pkg/apis/performanceprofile/v2/performanceprofile_validation_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
