Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-08, with the labels that each got.

#1377 OCPBUGS-60258: Return 401 Unauthorized without client cert
  pkg/metrics/server.go
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1379 NO-JIRA: Fix hack/update-codegen.sh
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/typed/tuned/v1/tuned_client.go
  pkg/generated/informers/externalversions/tuned/v1/profile.go
  pkg/generated/informers/externalversions/tuned/v1/tuned.go
  tools/tools.go
  vendor/k8s.io/code-generator/cmd/validation-gen/lint.go
  vendor/k8s.io/code-generator/cmd/validation-gen/main.go
  vendor/k8s.io/code-generator/cmd/validation-gen/targets.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validation.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/common.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/each.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/immutable.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/limits.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/opaque.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/registry.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/required.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/subfield.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/testing.go
  vendor/k8s.io/code-generator/cmd/validation-gen/validators/validators.go
  vendor/k8s.io/gengo/v2/parser/tags/json.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#1363 OCPBUGS-60838: e2e: arm: add validation tests for hugepages with 4k and 64k kernelPageSize
  test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go
  test/e2e/performanceprofile/functests/14_arm/hugepages.go
  test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
