Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-05, with the labels that each got.

#1289 NO-JIRA:e2e:daemonset: pod phase and events
  test/e2e/performanceprofile/functests/5_latency_testing/5_latency_testing_suite_test.go
  test/e2e/performanceprofile/functests/utils/daemonset/daemonset.go
  test/e2e/performanceprofile/functests/utils/images/prepull.go
  test/e2e/performanceprofile/functests/utils/node_inspector/inspector.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1302 OCPBUGS-55989: E2E: Functional tests for align cpus by UncoreCache Feature
  test/e2e/performanceprofile/functests/13_llc/llc.go
  test/e2e/performanceprofile/functests/utils/deployments/deployments.go
  test/e2e/performanceprofile/functests/utils/log/log.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#1326 OCPBUGS-56416: E2E: use 4 cpus for reserved from available cpus
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1330 OCPBUGS-56852: e2e: arm: fix ginkgo doesn't recognize kernelPageSize suite
  test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
