Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-01, with the labels that each got.

#1265 OCPBUGS-47683: [release-4.15][manual]: Fix context deadlines in ExecCommandOnPod()
  test/e2e/performanceprofile/functests/utils/pods/pods.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1258 OCPBUGS-46584: Adjust Workload Hints test cases based on Intel or AMD
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/utils/infrastructure/cpu.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1268 OCPBUGS-47701:[release-4.16] cmd: PPC: support tolerating heterogeneous core IDs
  cmd/performance-profile-creator/cmd/root.go
  pkg/performanceprofile/profilecreator/helper.go
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1270 OCPBUGS-45903: [release-4.18] PPC: correct EnableHardwareTuning flag value
  cmd/performance-profile-creator/cmd/root.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1271 OCPBUGS-44644: [release-4.17] PPC: correct EnableHardwareTuning flag value
  cmd/performance-profile-creator/cmd/root.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1273 OCPBUGS-48144:[release-4.16][manual]:e2e:performance: decode to valid kubeletconfig object
  pkg/util/manifests.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1275 OCPBUGS-48207:[release-4.15][manual]e2e:performance: decode to valid kubeletconfig object
  pkg/util/manifests.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1277 OCPBUGS-48213: [release-4.17][manual] Adjust Workload Hints test cases based on Intel or AMD
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/utils/infrastructure/cpu.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1276 OCPBUGS-48208: [release-4.14][manual]:e2e:performance: decode to valid kubeletconfig object
  pkg/util/manifest.go
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1281 OCPBUGS-48357: [release-4.16] [manual] Adjust Workload Hints test cases based on Intel or AMD
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
  test/e2e/performanceprofile/functests/utils/infrastructure/cpu.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1261 OCPBUGS-48317: PPC_Test_fix: use ROLE_WORKER_CNF environment variable to determine mcp name
  test/e2e/performanceprofile/functests/10_performance_ppc/ppc.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1280 OCPBUGS-48319: Add missing Polarion test case id
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1282 OCPBUGS-48422: [release-4.16] e2e: tuned degraded test fix
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/utils/infrastructure/vm.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1285 NO-JIRA: Fix hack/test-tuned-fdp.sh
  hack/test-tuned-fdp.sh
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1288 OCPBUGS-48722: [release-4.17] [manual] Add missing Polarion test case id
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/functests/8_performance_workloadhints/workloadhints.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/severity-low, jira/valid-bug, jira/valid-reference

#1284 OCPBUGS-48530: E2E: Add test cases to verify PerPodPowerManagement with PPC
  test/e2e/performanceprofile/functests/10_performance_ppc/ppc.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
