Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-03, with the labels that each got.

#1297 CNF-12525: Switch builder image to multi-arch image
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#1217 NO-JIRA: PPC: unit: test sortTopology for expected output
  .gitignore
  pkg/performanceprofile/profilecreator/profilecreator.go
  pkg/performanceprofile/profilecreator/profilecreator_test.go
Labels: lgtm, approved, jira/valid-reference

#1303 OCPBUGS-52352: Treat all aarch64 platforms as equals in tuned
  assets/performanceprofile/tuned/openshift-node-performance
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1216 OCPBUGS-44559: Manage TuneD profiles with the same name and different content
  manifests/20-profile.crd.yaml
  manifests/20-tuned.crd.yaml
  manifests/30-monitoring.yaml
  manifests/40-rbac.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/apis/tuned/v1/zz_generated.deepcopy.go
  pkg/metrics/metrics.go
  pkg/operator/controller.go
  pkg/operator/profilecalculator.go
  pkg/operator/profilecalculator_test.go
  pkg/operator/status.go
  pkg/operator/validator.go
  pkg/performanceprofile/controller/performanceprofile/status/status.go
  pkg/performanceprofile/controller/performanceprofile_controller_test.go
  pkg/tuned/controller.go
  pkg/tuned/status.go
  pkg/tuned/status_test.go
  test/e2e/basic/tuned_duplicate_profile.go
  test/e2e/deferred/operator_test.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/testing_manifests/conflict-01.yaml
  test/e2e/testing_manifests/conflict-02.yaml
  test/e2e/util/util.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1305 NO-JIRA: Add observedGeneration to Profile status
  manifests/20-profile.crd.yaml
  pkg/apis/tuned/v1/tuned_types.go
  pkg/tuned/controller.go
Labels: lgtm, approved, jira/valid-reference

#1301 CNF-16638: Reduce code duplication of RPS enabled checks
  hack/render-sync.sh
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/performanceprofile/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/performanceprofile/controller/performanceprofile/components/profile/profile.go
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance-norps/kustomization.yaml
  test/e2e/performanceprofile/cluster-setup/manual-cluster/performance-norps/performance_profile.yaml
  test/e2e/performanceprofile/functests-render-command/1_render_command/render_test.go
  test/e2e/performanceprofile/functests/1_performance/performance.go
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_kubeletconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_machineconfig.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_node.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_runtimeclass.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_tuned.yaml
Labels: lgtm, approved, jira/valid-reference

#1312 NO-JIRA: e2e: skip irqbalance tests due to known issue
  test/e2e/performanceprofile/functests/1_performance/irqbalance.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#1307 CNF-16013: e2e: arm: Add arm kernelPageSize e2e testing suite
  Makefile
  test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
  test/e2e/performanceprofile/functests/14_arm/test_suite_arm_test.go
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
