Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-07, with the labels that each got.

#1354 OCPBUGS-52853: Do not add iommu.passthrough to ARM by default
  assets/performanceprofile/tuned/openshift-node-performance-arm-aarch64
  pkg/performanceprofile/controller/performanceprofile/components/tuned/tuned_test.go
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/extra-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-master_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/bootstrap/no-mcp/openshift-bootstrap-worker_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/arm/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/cpuFrequency/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/default/pp-norps/manual_tuned.yaml
  test/e2e/performanceprofile/testdata/render-expected-output/no-ref/manual_tuned.yaml
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#1353 NO-JIRA: Add support for running binaries from NVIDIA driver directory
  pkg/tuned/controller.go
  pkg/tuned/run.go
  pkg/util/os.go
  pkg/util/os_test.go
Labels: lgtm, approved, jira/valid-reference

#1355 OCPBUGS-58346: [release-4.18] [manual] e2e: arm: Add arm kernelPageSize e2e testing suite
  Makefile
  test/e2e/performanceprofile/functests/14_arm/14_arm_suite_test.go
  test/e2e/performanceprofile/functests/14_arm/kernelpagesize.go
  test/e2e/performanceprofile/functests/utils/label/label.go
Labels: lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1361 OCPBUGS-59354: E2E add test to verify guaranteed pod is running after kubelet restart
  test/e2e/performanceprofile/functests/1_performance/cpu_management.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1368 NO-JIRA: Sync the upstream and downstream Containerfiles
  Dockerfile
Labels: lgtm, approved, jira/valid-reference
