Repository openshift/cluster-node-tuning-operator, pull requests merged in 2025-09, with the labels that each got.

#1382 NO-JIRA: E2E: llc: Create testing namespace before Runtime tests
  test/e2e/performanceprofile/functests/13_llc/llc.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only, verified

#1390 NO-JIRA:e2e: set of fixes/changes to ovs pinning testing
  test/e2e/performanceprofile/functests/7_performance_kubelet_node/cgroups.go
  test/e2e/performanceprofile/functests/utils/nodes/nodes.go
Labels: lgtm, approved, jira/valid-reference, verified

#1396 OCPBUGS-62091: E2E: Add function to check control plane nodes are schedulable.
  test/e2e/performanceprofile/functests/2_performance_update/updating_profile.go
  test/e2e/performanceprofile/functests/utils/cluster/cluster.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, verified
